
export const BEGINNER_NEPALI_DATA = [
  {"word": "Water", "pronunciation": "/ˈwɔːtər/", "meaning": "पानी", "english_sentence": "I drink water.", "native_sentence": "म पानी पिउँछु।", "synonym": "Aqua"},
  {"word": "School", "pronunciation": "/skuːl/", "meaning": "विद्यालय", "english_sentence": "The school is big.", "native_sentence": "विद्यालय ठूलो छ।", "synonym": "Academy"},
  {"word": "Book", "pronunciation": "/bʊk/", "meaning": "किताब", "english_sentence": "I read a book.", "native_sentence": "म किताब पढ्छु।", "synonym": "Volume"},
  {"word": "Friend", "pronunciation": "/frend/", "meaning": "साथी", "english_sentence": "He is my friend.", "native_sentence": "उनी मेरो साथी हुन्।", "synonym": "Buddy"},
  {"word": "House", "pronunciation": "/haʊs/", "meaning": "घर", "english_sentence": "My house is clean.", "native_sentence": "मेरो घर सफा छ।", "synonym": "Home"},
  {"word": "Eat", "pronunciation": "/iːt/", "meaning": "खानु", "english_sentence": "I eat an apple.", "native_sentence": "म स्याउ खान्छु।", "synonym": "Consume"},
  {"word": "Sleep", "pronunciation": "/sliːp/", "meaning": "सुत्नु", "english_sentence": "I sleep at night.", "native_sentence": "म राती सुत्छु।", "synonym": "Rest"},
  {"word": "Run", "pronunciation": "/rʌn/", "meaning": "दौडनु", "english_sentence": "He can run fast.", "native_sentence": "उनी छिटो दौडन सक्छन्।", "synonym": "Dash"},
  {"word": "Sun", "pronunciation": "/sʌn/", "meaning": "घाम", "english_sentence": "The sun is hot.", "native_sentence": "घाम तातो छ।", "synonym": "Sol"},
  {"word": "Sky", "pronunciation": "/skaɪ/", "meaning": "आकाश", "english_sentence": "The sky is blue.", "native_sentence": "आकाश नीलो छ।", "synonym": "Heavens"},
  {"word": "Tree", "pronunciation": "/triː/", "meaning": "रूख", "english_sentence": "The tree is tall.", "native_sentence": "रूख अग्लो छ।", "synonym": "Plant"},
  {"word": "Flower", "pronunciation": "/ˈflaʊər/", "meaning": "फूल", "english_sentence": "This flower is beautiful.", "native_sentence": "यो फूल सुन्दर छ।", "synonym": "Bloom"},
  {"word": "Milk", "pronunciation": "/mɪlk/", "meaning": "दूध", "english_sentence": "Milk is good for health.", "native_sentence": "दूध स्वास्थ्यका लागि राम्रो छ।", "synonym": "Dairy"},
  {"word": "Mother", "pronunciation": "/ˈmʌðər/", "meaning": "आमा", "english_sentence": "I love my mother.", "native_sentence": "म मेरो आमालाई माया गर्छु।", "synonym": "Mom"},
  {"word": "Father", "pronunciation": "/ˈfɑːðər/", "meaning": "बुबा", "english_sentence": "My father is kind.", "native_sentence": "मेरो बुबा दयालु हुनुहुन्छ।", "synonym": "Dad"},
  {"word": "Bird", "pronunciation": "/bɜːrd/", "meaning": "चरा", "english_sentence": "The bird can fly.", "native_sentence": "चरा उड्न सक्छ।", "synonym": "Fowl"},
  {"word": "Dog", "pronunciation": "/dɔːɡ/", "meaning": "कुकुर", "english_sentence": "The dog is barking.", "native_sentence": "कुकुर भुकिरहेको छ।", "synonym": "Canine"},
  {"word": "Cat", "pronunciation": "/kæt/", "meaning": "बिरालो", "english_sentence": "The cat is sleeping.", "native_sentence": "बिरालो सुतिरहेको छ।", "synonym": "Feline"},
  {"word": "Fish", "pronunciation": "/fɪʃ/", "meaning": "माछा", "english_sentence": "The fish lives in water.", "native_sentence": "माछा पानीमा बस्छ।", "synonym": "Seafood"},
  {"word": "Road", "pronunciation": "/roʊd/", "meaning": "सडक", "english_sentence": "The road is long.", "native_sentence": "सडक लामो छ।", "synonym": "Street"},
  {"word": "Car", "pronunciation": "/kɑːr/", "meaning": "गाडी", "english_sentence": "I have a red car.", "native_sentence": "मसँग रातो गाडी छ।", "synonym": "Vehicle"},
  {"word": "Apple", "pronunciation": "/ˈæpəl/", "meaning": "स्याउ", "english_sentence": "The apple is sweet.", "native_sentence": "स्याउ गुलियो छ।", "synonym": "Fruit"},
  {"word": "Pencil", "pronunciation": "/ˈpensəl/", "meaning": "सिसाकलम", "english_sentence": "I write with a pencil.", "native_sentence": "म सिसाकलमले लेख्छु।", "synonym": "Writer"},
  {"word": "Paper", "pronunciation": "/ˈpeɪpər/", "meaning": "कागज", "english_sentence": "Write on the paper.", "native_sentence": "कागजमा लेख्नुहोस्।", "synonym": "Sheet"},
  {"word": "Day", "pronunciation": "/deɪ/", "meaning": "दिन", "english_sentence": "It is a sunny day.", "native_sentence": "यो एउटा घमाइलो दिन हो।", "synonym": "Daytime"},
  {"word": "Night", "pronunciation": "/naɪt/", "meaning": "रात", "english_sentence": "The stars shine at night.", "native_sentence": "रातमा ताराहरू चम्किन्छन्।", "synonym": "Darkness"},
  {"word": "Hand", "pronunciation": "/hænd/", "meaning": "हात", "english_sentence": "Wash your hand.", "native_sentence": "आफ्नो हात धुनुहोस्।", "synonym": "Palm"},
  {"word": "Foot", "pronunciation": "/fʊt/", "meaning": "खुट्टा", "english_sentence": "He hurt his foot.", "native_sentence": "उनको खुट्टामा चोट लाग्यो।", "synonym": "Paw"},
  {"word": "Eye", "pronunciation": "/aɪ/", "meaning": "आँखा", "english_sentence": "Close your eye.", "native_sentence": "आफ्नो आँखा बन्द गर्नुहोस्।", "synonym": "Optic"},
  {"word": "Ear", "pronunciation": "/ɪər/", "meaning": "कान", "english_sentence": "Listen with your ear.", "native_sentence": "आफ्नो कानले सुन्नुहोस्।", "synonym": "Aural"},
  {"word": "Strong", "pronunciation": "/strɔːŋ/", "meaning": "बलियो", "english_sentence": "He is very strong.", "native_sentence": "उनी धेरै बलियो छन्।", "synonym": "Powerful"},
  {"word": "Weak", "pronunciation": "/wiːk/", "meaning": "कमजोर", "english_sentence": "The bridge is weak.", "native_sentence": "पुल कमजोर छ।", "synonym": "Fragile"},
  {"word": "New", "pronunciation": "/njuː/", "meaning": "नयाँ", "english_sentence": "I bought a new shirt.", "native_sentence": "मैले नयाँ सर्ट किने।", "synonym": "Fresh"},
  {"word": "Old", "pronunciation": "/oʊld/", "meaning": "पुरानो", "english_sentence": "The book is old.", "native_sentence": "किताब पुरानो छ।", "synonym": "Ancient"},
  {"word": "Rich", "pronunciation": "/rɪtʃ/", "meaning": "धनी", "english_sentence": "He is a rich man.", "native_sentence": "उनी धनी मानिस हुन्।", "synonym": "Wealthy"},
  {"word": "Poor", "pronunciation": "/pɔːr/", "meaning": "गरिब", "english_sentence": "Help the poor people.", "native_sentence": "गरिब मानिसहरूलाई मद्दत गर्नुहोस्।", "synonym": "Needy"},
  {"word": "Hot", "pronunciation": "/hɒt/", "meaning": "तातो", "english_sentence": "The tea is hot.", "native_sentence": "चिया तातो छ।", "synonym": "Warm"},
  {"word": "Smile", "pronunciation": "/smaɪl/", "meaning": "मुस्कान", "english_sentence": "She has a nice smile.", "native_sentence": "उनको मुस्कान राम्रो छ।", "synonym": "Grin"},
  {"word": "Crying", "pronunciation": "/ˈkraɪɪŋ/", "meaning": "रोइरहेको", "english_sentence": "The baby is crying.", "native_sentence": "बच्चा रोइरहेको छ।", "synonym": "Weeping"},
  {"word": "Laugh", "pronunciation": "/læf/", "meaning": "हाँस्नु", "english_sentence": "We laugh together.", "native_sentence": "हामी सँगै हाँस्छौं।", "synonym": "Chuckle"},
  {"word": "Jump", "pronunciation": "/dʒʌmp/", "meaning": "उफ्रनु", "english_sentence": "Kids like to jump.", "native_sentence": "बच्चाहरू उफ्रन मन पराउँछन्।", "synonym": "Leap"},
  {"word": "Small", "pronunciation": "/smɔːl/", "meaning": "सानो", "english_sentence": "The ant is small.", "native_sentence": "कमिला सानो हुन्छ।", "synonym": "Tiny"},
  {"word": "Big", "pronunciation": "/bɪɡ/", "meaning": "ठूलो", "english_sentence": "That is a big elephant.", "native_sentence": "त्यो एउटा ठूलो हात्ती हो।", "synonym": "Huge"},
  {"word": "Play", "pronunciation": "/pleɪ/", "meaning": "खेल्नु", "english_sentence": "Let's play football.", "native_sentence": "फुटबल खेलौं।", "synonym": "Sport"},
  {"word": "Work", "pronunciation": "/wɜːrk/", "meaning": "काम", "english_sentence": "He goes to work.", "native_sentence": "उनी काममा जान्छन्।", "synonym": "Job"},
  {"word": "Stop", "pronunciation": "/stɒp/", "meaning": "रोकिनु", "english_sentence": "Stop the car here.", "native_sentence": "यहाँ गाडी रोक्नुहोस्।", "synonym": "Halt"},
  {"word": "Slow", "pronunciation": "/sloʊ/", "meaning": "ढिलो", "english_sentence": "The turtle is slow.", "native_sentence": "कछुवा ढिलो हुन्छ।", "synonym": "Leisurely"},
  {"word": "Quick", "pronunciation": "/kwɪk/", "meaning": "छिटो", "english_sentence": "Be quick, we are late.", "native_sentence": "छिटो गर्नुहोस्, ढिलो भइसक्यो।", "synonym": "Rapid"},
  {"word": "Happy", "pronunciation": "/ˈhæpi/", "meaning": "खुसी", "english_sentence": "I am very happy.", "native_sentence": "म धेरै खुसी छु।", "synonym": "Cheerful"},
  {"word": "Sad", "pronunciation": "/sæd/", "meaning": "दुखी", "english_sentence": "Don't be sad.", "native_sentence": "दुखी नहुनुहोस्।", "synonym": "Unhappy"},
  {"word": "Door", "pronunciation": "/dɔːr/", "meaning": "ढोका", "english_sentence": "Open the door.", "native_sentence": "ढोका खोल्नुहोस्।", "synonym": "Entrance"},
  {"word": "Window", "pronunciation": "/ˈwɪndoʊ/", "meaning": "झ्याल", "english_sentence": "Close the window.", "native_sentence": "झ्याल बन्द गर्नुहोस्।", "synonym": "Opening"},
  {"word": "Chair", "pronunciation": "/tʃeər/", "meaning": "कुर्सी", "english_sentence": "Sit on the chair.", "native_sentence": "कुर्सीमा बस्नुहोस्।", "synonym": "Seat"},
  {"word": "Table", "pronunciation": "/ˈteɪbəl/", "meaning": "टेबल", "english_sentence": "Put it on the table.", "native_sentence": "यसलाई टेबलमा राख्नुहोस्।", "synonym": "Desk"},
  {"word": "Bed", "pronunciation": "/bed/", "meaning": "ओछ्यान", "english_sentence": "The bed is soft.", "native_sentence": "ओछ्यान नरम छ।", "synonym": "Couch"},
  {"word": "Knife", "pronunciation": "/naɪf/", "meaning": "चक्कु", "english_sentence": "Be careful with the knife.", "native_sentence": "चक्कुसँग होसियार हुनुहोस्।", "synonym": "Blade"},
  {"word": "Spoon", "pronunciation": "/spuːn/", "meaning": "चम्चा", "english_sentence": "I eat with a spoon.", "native_sentence": "म चम्चाले खान्छु।", "synonym": "Scoop"},
  {"word": "Plate", "pronunciation": "/pleɪt/", "meaning": "थाल", "english_sentence": "The plate is empty.", "native_sentence": "थाल खाली छ।", "synonym": "Dish"},
  {"word": "Shirt", "pronunciation": "/ʃɜːrt/", "meaning": "कमिज", "english_sentence": "Your shirt is blue.", "native_sentence": "तपाईंको कमिज नीलो छ।", "synonym": "Top"},
  {"word": "Shoes", "pronunciation": "/ʃuːz/", "meaning": "जुत्ता", "english_sentence": "Put on your shoes.", "native_sentence": "आफ्नो जुत्ता लगाउनुहोस्।", "synonym": "Footwear"},
  {"word": "Bag", "pronunciation": "/bæɡ/", "meaning": "झोला", "english_sentence": "Carry your bag.", "native_sentence": "आफ्नो झोला बोक्नुहोस्।", "synonym": "Sack"},
  {"word": "Face", "pronunciation": "/feɪs/", "meaning": "अनुहार", "english_sentence": "Wash your face.", "native_sentence": "आफ्नो अनुहार धुनुहोस्।", "synonym": "Countenance"},
  {"word": "Hair", "pronunciation": "/heər/", "meaning": "कपाल", "english_sentence": "She has long hair.", "native_sentence": "उनको लामो कपाल छ।", "synonym": "Locks"},
  {"word": "Tooth", "pronunciation": "/tuːθ/", "meaning": "दाँत", "english_sentence": "Brush your tooth.", "native_sentence": "आफ्नो दाँत माझ्नुहोस्।", "synonym": "Ivory"},
  {"word": "Nose", "pronunciation": "/noʊz/", "meaning": "नाक", "english_sentence": "Breathe through your nose.", "native_sentence": "नाकबाट सास फेर्नुहोस्।", "synonym": "Snout"},
  {"word": "River", "pronunciation": "/ˈrɪvər/", "meaning": "खोला", "english_sentence": "The river is deep.", "native_sentence": "खोला गहिरो छ।", "synonym": "Stream"},
  {"word": "Mountain", "pronunciation": "/ˈmaʊntən/", "meaning": "पहाड", "english_sentence": "The mountain is high.", "native_sentence": "पहाड अग्लो छ।", "synonym": "Peak"},
  {"word": "Rain", "pronunciation": "/reɪn/", "meaning": "वर्षा", "english_sentence": "It is starting to rain.", "native_sentence": "वर्षा हुन थालेको छ।", "synonym": "Shower"},
  {"word": "Wind", "pronunciation": "/wɪnd/", "meaning": "हावा", "english_sentence": "The wind is cold.", "native_sentence": "हावा चिसो छ।", "synonym": "Breeze"},
  {"word": "Cloud", "pronunciation": "/klaʊd/", "meaning": "बादल", "english_sentence": "There are white clouds.", "native_sentence": "त्यहाँ सेता बादलहरू छन्।", "synonym": "Mist"},
  {"word": "Stone", "pronunciation": "/stoʊn/", "meaning": "ढुङ्गा", "english_sentence": "This stone is hard.", "native_sentence": "यो ढुङ्गा गाह्रो छ।", "synonym": "Rock"},
  {"word": "Grass", "pronunciation": "/ɡræs/", "meaning": "घाँस", "english_sentence": "Sit on the grass.", "native_sentence": "घाँसमा बस्नुहोस्।", "synonym": "Turf"},
  {"word": "Gold", "pronunciation": "/ɡoʊld/", "meaning": "सुन", "english_sentence": "Gold is expensive.", "native_sentence": "सुन महँगो हुन्छ।", "synonym": "Aurum"},
  {"word": "Iron", "pronunciation": "/ˈaɪərn/", "meaning": "फलाम", "english_sentence": "Iron is a strong metal.", "native_sentence": "फलाम एक बलियो धातु हो।", "synonym": "Steel"},
  {"word": "Bread", "pronunciation": "/bred/", "meaning": "रोटी", "english_sentence": "I like fresh bread.", "native_sentence": "मलाई ताजा रोटी मन पर्छ।", "synonym": "Loaf"},
  {"word": "Egg", "pronunciation": "/eɡ/", "meaning": "अण्डा", "english_sentence": "I eat an egg daily.", "native_sentence": "म दिनहुँ एउटा अण्डा खान्छु।", "synonym": "Ovum"},
  {"word": "Fruit", "pronunciation": "/fruːt/", "meaning": "फलफूल", "english_sentence": "Eat more fruit.", "native_sentence": "धेरै फलफूल खानुहोस्।", "synonym": "Produce"},
  {"word": "Vegetable", "pronunciation": "/ˈvedʒtəbəl/", "meaning": "तरकारी", "english_sentence": "Buy some vegetables.", "native_sentence": "केही तरकारीहरू किन्नुहोस्।", "synonym": "Greens"},
  {"word": "Salt", "pronunciation": "/sɔːlt/", "meaning": "नुन", "english_sentence": "Add some salt.", "native_sentence": "थोरै नुन हाल्नुहोस्।", "synonym": "Sodium"},
  {"word": "Sugar", "pronunciation": "/ˈʃʊɡər/", "meaning": "चिनी", "english_sentence": "Sugar is sweet.", "native_sentence": "चिनी गुलियो हुन्छ।", "synonym": "Sweetener"},
  {"word": "Sweet", "pronunciation": "/swiːt/", "meaning": "गुलियो", "english_sentence": "The cake is sweet.", "native_sentence": "केक गुलियो छ।", "synonym": "Sugary"},
  {"word": "Bitter", "pronunciation": "/ˈbɪtər/", "meaning": "तितो", "english_sentence": "This medicine is bitter.", "native_sentence": "यो औषधि तितो छ।", "synonym": "Acid"},
  {"word": "Open", "pronunciation": "/ˈoʊpən/", "meaning": "खोल्नु", "english_sentence": "Open your eyes.", "native_sentence": "आफ्नो आँखा खोल्नुहोस्।", "synonym": "Unlock"},
  {"word": "Close", "pronunciation": "/kloʊz/", "meaning": "बन्द गर्नु", "english_sentence": "Close the book.", "native_sentence": "किताब बन्द गर्नुहोस्।", "synonym": "Shut"},
  {"word": "Clean", "pronunciation": "/kliːn/", "meaning": "सफा", "english_sentence": "Keep your hands clean.", "native_sentence": "आफ्नो हात सफा राख्नुहोस्।", "synonym": "Tidy"},
  {"word": "Dirty", "pronunciation": "/ˈdɜːrti/", "meaning": "फोहोर", "english_sentence": "Your clothes are dirty.", "native_sentence": "तपाईंका लुगाहरू फोहोर छन्।", "synonym": "Filthy"},
  {"word": "Tall", "pronunciation": "/tɔːl/", "meaning": "अग्लो", "english_sentence": "He is very tall.", "native_sentence": "उनी धेरै अग्ला छन्।", "synonym": "High"},
  {"word": "Short", "pronunciation": "/ʃɔːrt/", "meaning": "होचो", "english_sentence": "The boy is short.", "native_sentence": "केटो होचो छ।", "synonym": "Brief"},
  {"word": "Full", "pronunciation": "/fʊl/", "meaning": "भरिएको", "english_sentence": "The glass is full.", "native_sentence": "ग्लास भरिएको छ।", "synonym": "Packed"},
  {"word": "Empty", "pronunciation": "/ˈempti/", "meaning": "खाली", "english_sentence": "The box is empty.", "native_sentence": "बक्स खाली छ।", "synonym": "Vacant"},
  {"word": "Hear", "pronunciation": "/hɪər/", "meaning": "सुन्नु", "english_sentence": "Can you hear me?", "native_sentence": "के तपाईं मलाई सुन्न सक्नुहुन्छ?", "synonym": "Listen"},
  {"word": "See", "pronunciation": "/siː/", "meaning": "देख्नु", "english_sentence": "I see a bird.", "native_sentence": "म एउटा चरा देख्छु।", "synonym": "View"},
  {"word": "Wait", "pronunciation": "/weɪt/", "meaning": "पर्खनु", "english_sentence": "Please wait for me.", "native_sentence": "कृपया मलाई पर्खनुहोस्।", "synonym": "Pause"},
  {"word": "Speak", "pronunciation": "/spiːk/", "meaning": "बोल्नु", "english_sentence": "Speak slowly please.", "native_sentence": "कृपया बिस्तारै बोल्नुहोस्।", "synonym": "Talk"},
  {"word": "Write", "pronunciation": "/raɪt/", "meaning": "लेख्नु", "english_sentence": "Write your name.", "native_sentence": "आफ्नो नाम लेख्नुहोस्।", "synonym": "Note"},
  {"word": "Read", "pronunciation": "/riːd/", "meaning": "पढ्नु", "english_sentence": "Read the lesson.", "native_sentence": "पाठ पढ्नुहोस्।", "synonym": "Study"},
  {"word": "Buy", "pronunciation": "/baɪ/", "meaning": "किन्नु", "english_sentence": "I want to buy a pen.", "native_sentence": "म एउटा कलम किन्न चाहन्छु।", "synonym": "Purchase"},
  {"word": "Sell", "pronunciation": "/sel/", "meaning": "बेच्नु", "english_sentence": "He sells apples.", "native_sentence": "उनी स्याउ बेच्छन्।", "synonym": "Trade"},
  {"word": "Walk", "pronunciation": "/wɔːk/", "meaning": "हिँड्नु", "english_sentence": "Walk every morning.", "native_sentence": "हरेक बिहान हिँड्नुहोस्।", "synonym": "Stroll"},
  {"word": "Sit", "pronunciation": "/sɪt/", "meaning": "बस्नु", "english_sentence": "Sit down please.", "native_sentence": "कृपया बस्नुहोस्।", "synonym": "Rest"},
  {"word": "Morning", "pronunciation": "/ˈmɔːrnɪŋ/", "meaning": "बिहान", "english_sentence": "I wake up in the morning.", "native_sentence": "म बिहान उठ्छु।", "synonym": "Dawn"},
  {"word": "Evening", "pronunciation": "/ˈiːvnɪŋ/", "meaning": "बेलुका", "english_sentence": "We walk in the evening.", "native_sentence": "हामी बेलुका हिँड्छौं।", "synonym": "Dusk"},
  {"word": "Week", "pronunciation": "/wiːk/", "meaning": "हप्ता", "english_sentence": "There are seven days in a week.", "native_sentence": "एक हप्तामा सात दिन हुन्छन्।", "synonym": "Cycle"},
  {"word": "Month", "pronunciation": "/mʌnθ/", "meaning": "महिना", "english_sentence": "January is the first month.", "native_sentence": "जनवरी पहिलो महिना हो।", "synonym": "Period"},
  {"word": "Year", "pronunciation": "/jɪər/", "meaning": "वर्ष", "english_sentence": "Happy new year.", "native_sentence": "नयाँ वर्षको शुभकामना।", "synonym": "Era"},
  {"word": "Bicycle", "pronunciation": "/ˈbaɪsɪkl/", "meaning": "साइकल", "english_sentence": "I ride my bicycle.", "native_sentence": "म मेरो साइकल चलाउँछु।", "synonym": "Cycle"},
  {"word": "Bus", "pronunciation": "/bʌs/", "meaning": "बस", "english_sentence": "The bus is late.", "native_sentence": "बस ढिलो छ।", "synonym": "Coach"},
  {"word": "Airplane", "pronunciation": "/ˈerpleɪn/", "meaning": "हवाईजहाज", "english_sentence": "The airplane is in the sky.", "native_sentence": "हवाईजहाज आकाशमा छ।", "synonym": "Aircraft"},
  {"word": "Boat", "pronunciation": "/boʊt/", "meaning": "ढुङ्गा", "english_sentence": "The boat is on the lake.", "native_sentence": "ढुङ्गा तालमा छ।", "synonym": "Ship"},
  {"word": "Head", "pronunciation": "/hed/", "meaning": "टाउको", "english_sentence": "Protect your head.", "native_sentence": "आफ्नो टाउको बचाउनुहोस्।", "synonym": "Skull"},
  {"word": "Shoulder", "pronunciation": "/ˈʃoʊldər/", "meaning": "काँध", "english_sentence": "He has broad shoulders.", "native_sentence": "उनको फराकिलो काँध छ।", "synonym": "Joint"},
  {"word": "Arm", "pronunciation": "/ɑːrm/", "meaning": "हात (पाखुरा)", "english_sentence": "Stretch your arm.", "native_sentence": "आफ्नो पाखुरा तन्काउनुहोस्।", "synonym": "Limb"},
  {"word": "Leg", "pronunciation": "/leɡ/", "meaning": "खुट्टा", "english_sentence": "My leg is hurting.", "native_sentence": "मेरो खुट्टा दुखिरहेको छ।", "synonym": "Member"},
  {"word": "Finger", "pronunciation": "/ˈfɪŋɡər/", "meaning": "औंला", "english_sentence": "I have ten fingers.", "native_sentence": "मेरो १० वटा औंलाहरू छन्।", "synonym": "Digit"},
  {"word": "Medicine", "pronunciation": "/ˈmedsn/", "meaning": "औषधि", "english_sentence": "Take your medicine.", "native_sentence": "आफ्नो औषधि खानुहोस्।", "synonym": "Drug"},
  {"word": "Doctor", "pronunciation": "/ˈdɒktər/", "meaning": "डाक्टर", "english_sentence": "Go to the doctor.", "native_sentence": "डाक्टरकहाँ जानुहोस्।", "synonym": "Physician"},
  {"word": "City", "pronunciation": "/ˈsɪti/", "meaning": "सहर", "english_sentence": "Kathmandu is a city.", "native_sentence": "काठमाडौं एउटा सहर हो।", "synonym": "Town"},
  {"word": "Village", "pronunciation": "/ˈvɪlɪdʒ/", "meaning": "गाउँ", "english_sentence": "My village is small.", "native_sentence": "मेरो गाउँ सानो छ।", "synonym": "Hamlet"},
  {"word": "Market", "pronunciation": "/ˈmɑːrkɪt/", "meaning": "बजार", "english_sentence": "The market is crowded.", "native_sentence": "बजारमा भीड छ।", "synonym": "Bazaar"},
  {"word": "Shop", "pronunciation": "/ʃɒp/", "meaning": "पसल", "english_sentence": "The shop is open.", "native_sentence": "पसल खुला छ।", "synonym": "Store"},
  {"word": "Money", "pronunciation": "/ˈmʌni/", "meaning": "पैसा", "english_sentence": "I need some money.", "native_sentence": "मलाई केही पैसा चाहिन्छ।", "synonym": "Cash"},
  {"word": "Price", "pronunciation": "/praɪs/", "meaning": "मूल्य", "english_sentence": "What is the price?", "native_sentence": "यसको मूल्य कति हो?", "synonym": "Cost"},
  {"word": "Heavy", "pronunciation": "/ˈhevi/", "meaning": "गह्रौं", "english_sentence": "This box is heavy.", "native_sentence": "यो बक्स गह्रौं छ।", "synonym": "Weighty"},
  {"word": "Light", "pronunciation": "/laɪt/", "meaning": "हल्का", "english_sentence": "The bag is light.", "native_sentence": "झोला हल्का छ।", "synonym": "Weightless"},
  {"word": "Fast", "pronunciation": "/fæst/", "meaning": "छिटो", "english_sentence": "He runs fast.", "native_sentence": "उनी छिटो दौडिन्छन्।", "synonym": "Rapid"},
  {"word": "Dry", "pronunciation": "/draɪ/", "meaning": "सुख्खा", "english_sentence": "The cloth is dry.", "native_sentence": "कपडा सुख्खा छ।", "synonym": "Arid"},
  {"word": "Wet", "pronunciation": "/wet/", "meaning": "भिजेको", "english_sentence": "The floor is wet.", "native_sentence": "भुइँ भिजेको छ।", "synonym": "Damp"},
  {"word": "Easy", "pronunciation": "/ˈiːzi/", "meaning": "सजिलो", "english_sentence": "This task is easy.", "native_sentence": "यो कार्य सजिलो छ।", "synonym": "Simple"},
  {"word": "Hard", "pronunciation": "/hɑːrd/", "meaning": "गाह्रो", "english_sentence": "The exam was hard.", "native_sentence": "परीक्षा गाह्रो थियो।", "synonym": "Difficult"},
  {"word": "Soft", "pronunciation": "/sɒft/", "meaning": "नरम", "english_sentence": "The pillow is soft.", "native_sentence": "सिरानी नरम छ।", "synonym": "Smooth"},
  {"word": "Rough", "pronunciation": "/rʌf/", "meaning": "खस्रो", "english_sentence": "The wall is rough.", "native_sentence": "भित्ता खस्रो छ।", "synonym": "Coarse"},
  {"word": "Safe", "pronunciation": "/seɪf/", "meaning": "सुरक्षित", "english_sentence": "Drive safe.", "native_sentence": "सुरक्षित रूपमा सवारी चलाउनुहोस्।", "synonym": "Secure"},
  {"word": "Think", "pronunciation": "/θɪŋk/", "meaning": "सोच्नु", "english_sentence": "Think before you speak.", "native_sentence": "बोल्नु अघि सोच्नुहोस्।", "synonym": "Ponder"},
  {"word": "Learn", "pronunciation": "/lɜːrn/", "meaning": "सिक्नु", "english_sentence": "I want to learn English.", "native_sentence": "म अंग्रेजी सिक्न चाहन्छु।", "synonym": "Gain"},
  {"word": "Teach", "pronunciation": "/tiːtʃ/", "meaning": "सिकाउनु", "english_sentence": "She will teach us.", "native_sentence": "उनले हामीलाई सिकाउनेछिन्।", "synonym": "Instruct"},
  {"word": "Find", "pronunciation": "/faɪnd/", "meaning": "फेला पार्नु", "english_sentence": "I can't find my keys.", "native_sentence": "मैले मेरो साँचो फेला पार्न सकिन।", "synonym": "Discover"},
  {"word": "Lose", "pronunciation": "/luːz/", "meaning": "हराउनु", "english_sentence": "Don't lose your phone.", "native_sentence": "आफ्नो फोन नहराउनुहोस्।", "synonym": "Misplace"},
  {"word": "Give", "pronunciation": "/ɡɪv/", "meaning": "दिनु", "english_sentence": "Give me a pen.", "native_sentence": "मलाई एउटा कलम दिनुहोस्।", "synonym": "Grant"},
  {"word": "Take", "pronunciation": "/teɪk/", "meaning": "लिनु", "english_sentence": "Take a seat.", "native_sentence": "बस्नुहोस् (सिट लिनुहोस्)।", "synonym": "Fetch"},
  {"word": "Dream", "pronunciation": "/driːm/", "meaning": "सपना", "english_sentence": "I had a good dream.", "native_sentence": "मैले राम्रो सपना देखेँ।", "synonym": "Vision"},
  {"word": "Answer", "pronunciation": "/ˈɑːnsər/", "meaning": "उत्तर", "english_sentence": "Give me an answer.", "native_sentence": "मलाई एउटा उत्तर दिनुहोस्।", "synonym": "Reply"},
  {"word": "Question", "pronunciation": "/ˈkwestʃən/", "meaning": "प्रश्न", "english_sentence": "Ask a question.", "native_sentence": "एउटा प्रश्न सोध्नुहोस्।", "synonym": "Inquiry"},
  {"word": "Wall", "pronunciation": "/wɔːl/", "meaning": "भित्ता", "english_sentence": "The wall is white.", "native_sentence": "भित्ता सेतो छ।", "synonym": "Partition"},
  {"word": "Floor", "pronunciation": "/flɔːr/", "meaning": "भुइँ", "english_sentence": "Clean the floor.", "native_sentence": "भुइँ सफा गर्नुहोस्।", "synonym": "Deck"},
  {"word": "Roof", "pronunciation": "/ruːf/", "meaning": "छत", "english_sentence": "The roof is leaking.", "native_sentence": "छत चुहिरहेको छ।", "synonym": "Ceiling"},
  {"word": "Earth", "pronunciation": "/ɜːrθ/", "meaning": "पृथ्वी", "english_sentence": "We live on Earth.", "native_sentence": "हामी पृथ्वीमा बस्छौं।", "synonym": "Planet"},
  {"word": "Bowl", "pronunciation": "/boʊl/", "meaning": "कचौरा", "english_sentence": "Put the soup in a bowl.", "native_sentence": "सूप कचौरामा राख्नुहोस्।", "synonym": "Basin"},
  {"word": "Cup", "pronunciation": "/kʌp/", "meaning": "कप", "english_sentence": "I want a cup of tea.", "native_sentence": "मलाई एक कप चिया चाहिन्छ।", "synonym": "Mug"},
  {"word": "Glass", "pronunciation": "/ɡlæs/", "meaning": "ग्लास", "english_sentence": "Fill the glass with water.", "native_sentence": "ग्लासमा पानी भर्नुहोस्।", "synonym": "Tumbler"},
  {"word": "Stove", "pronunciation": "/stoʊv/", "meaning": "चुलो", "english_sentence": "Turn off the stove.", "native_sentence": "चुलो निभाउनुहोस्।", "synonym": "Burner"},
  {"word": "Angry", "pronunciation": "/ˈæŋɡri/", "meaning": "रिसाएको", "english_sentence": "Why are you angry?", "native_sentence": "तपाईं किन रिसाउनुभएको छ?", "synonym": "Mad"},
  {"word": "Brave", "pronunciation": "/breɪv/", "meaning": "बहादुर", "english_sentence": "He is a brave soldier.", "native_sentence": "उनी एक बहादुर सिपाही हुन्।", "synonym": "Courageous"},
  {"word": "Hungry", "pronunciation": "/ˈhʌŋɡri/", "meaning": "भोको", "english_sentence": "I am very hungry.", "native_sentence": "म धेरै भोको छु।", "synonym": "Starving"},
  {"word": "Thirsty", "pronunciation": "/ˈθɜːrsti/", "meaning": "तिर्खाएको", "english_sentence": "Drink water if you are thirsty.", "native_sentence": "तिर्खा लागेको छ भने पानी पिउनुहोस्।", "synonym": "Parched"},
  {"word": "Tired", "pronunciation": "/ˈtaɪərd/", "meaning": "थकित", "english_sentence": "I am tired after work.", "native_sentence": "म काम पछि थकित छु।", "synonym": "Sleepy"},
  {"word": "Ugly", "pronunciation": "/ˈʌɡli/", "meaning": "कुरुप", "english_sentence": "That is an ugly bug.", "native_sentence": "त्यो एउटा कुरुप कीरा हो।", "synonym": "Hideous"},
  {"word": "Funny", "pronunciation": "/ˈfʌni/", "meaning": "रमाइलो", "english_sentence": "Tell me a funny story.", "native_sentence": "मलाई एउटा रमाइलो कथा सुनाउनुहोस्।", "synonym": "Humorous"},
  {"word": "Serious", "pronunciation": "/ˈsɪəriəs/", "meaning": "गम्भीर", "english_sentence": "He looks very serious.", "native_sentence": "उनी धेरै गम्भीर देखिन्छन्।", "synonym": "Solemn"},
  {"word": "Bank", "pronunciation": "/bæŋk/", "meaning": "बैंक", "english_sentence": "I need to go to the bank.", "native_sentence": "म बैंक जानुपर्छ।", "synonym": "Treasury"},
  {"word": "Hospital", "pronunciation": "/ˈhɒspɪtl/", "meaning": "अस्पताल", "english_sentence": "The hospital is near here.", "native_sentence": "अस्पताल यहाँ नजिकै छ।", "synonym": "Clinic"},
  {"word": "Temple", "pronunciation": "/ˈtempl/", "meaning": "मन्दिर", "english_sentence": "People go to the temple to pray.", "native_sentence": "मानिसहरू प्रार्थना गर्न मन्दिर जान्छन्।", "synonym": "Shrine"},
  {"word": "Bridge", "pronunciation": "/brɪdʒ/", "meaning": "पुल", "english_sentence": "Cross the bridge slowly.", "native_sentence": "बिस्तारै पुल तर्नुहोस्।", "synonym": "Overpass"},
  {"word": "Park", "pronunciation": "/pɑːrk/", "meaning": "पार्क", "english_sentence": "Let's sit in the park.", "native_sentence": "पार्कमा बसौं।", "synonym": "Garden"},
  {"word": "Field", "pronunciation": "/fiːld/", "meaning": "बारी (खेत)", "english_sentence": "The farmer is in the field.", "native_sentence": "किसान खेतमा छ।", "synonym": "Meadow"},
  {"word": "Hill", "pronunciation": "/hɪl/", "meaning": "डाँडा", "english_sentence": "We climbed the hill.", "native_sentence": "हामी डाँडामा चढ्यौं।", "synonym": "Mound"},
  {"word": "Sand", "pronunciation": "/sænd/", "meaning": "बालुवा", "english_sentence": "The children play in the sand.", "native_sentence": "बच्चाहरू बालुवामा खेल्छन्।", "synonym": "Grit"},
  {"word": "Sunlight", "pronunciation": "/ˈsʌnlaɪt/", "meaning": "घाम", "english_sentence": "I enjoy the sunlight.", "native_sentence": "म घामको आनन्द लिन्छु।", "synonym": "Sunshine"},
  {"word": "Air", "pronunciation": "/eər/", "meaning": "हावा", "english_sentence": "Fresh air is good for you.", "native_sentence": "ताजा हावा तपाईंको लागि राम्रो छ।", "synonym": "Breeze"},
  {"word": "Country", "pronunciation": "/ˈkʌntri/", "meaning": "देश", "english_sentence": "Nepal is my country.", "native_sentence": "नेपाल मेरो देश हो।", "synonym": "Nation"},
  {"word": "Language", "pronunciation": "/ˈlæŋɡwɪdʒ/", "meaning": "भाषा", "english_sentence": "Which language do you speak?", "native_sentence": "तपाईं कुन भाषा बोल्नुहुन्छ?", "synonym": "Tongue"},
  {"word": "Word", "pronunciation": "/wɜːrd/", "meaning": "शब्द", "english_sentence": "Learn a new word.", "native_sentence": "नयाँ शब्द सिक्नुहोस्।", "synonym": "Term"},
  {"word": "Letter", "pronunciation": "/ˈletər/", "meaning": "चिट्ठी (वा अक्षर)", "english_sentence": "I wrote a letter.", "native_sentence": "मैले एउटा चिट्ठी लेखें।", "synonym": "Note"},
  {"word": "Minute", "pronunciation": "/ˈmɪnɪt/", "meaning": "मिनेट", "english_sentence": "Wait for one minute.", "native_sentence": "एक मिनेट पर्खनुहोस्।", "synonym": "Moment"},
  {"word": "Hour", "pronunciation": "/ˈaʊər/", "meaning": "घण्टा", "english_sentence": "I study for an hour.", "native_sentence": "म एक घण्टा पढ्छु।", "synonym": "Time"},
  {"word": "Life", "pronunciation": "/laɪf/", "meaning": "जीवन", "english_sentence": "Life is beautiful.", "native_sentence": "जीवन सुन्दर छ।", "synonym": "Existence"},
  {"word": "Death", "pronunciation": "/deθ/", "meaning": "मृत्यु", "english_sentence": "Death is natural.", "native_sentence": "मृत्यु प्राकृतिक हो।", "synonym": "End"},
  {"word": "War", "pronunciation": "/wɔːr/", "meaning": "युद्ध", "english_sentence": "War is bad.", "native_sentence": "युद्ध नराम्रो हो।", "synonym": "Battle"},
  {"word": "Peace", "pronunciation": "/piːs/", "meaning": "शान्ति", "english_sentence": "We want peace.", "native_sentence": "हामी शान्ति चाहन्छौं।", "synonym": "Calm"},
  {"word": "News", "pronunciation": "/njuːz/", "meaning": "समाचार", "english_sentence": "I watch the news.", "native_sentence": "म समाचार हेर्छु।", "synonym": "Report"},
  {"word": "Story", "pronunciation": "/ˈstɔːri/", "meaning": "कथा", "english_sentence": "Read me a story.", "native_sentence": "मलाई एउटा कथा पढ्नुहोस्।", "synonym": "Tale"},
  {"word": "Song", "pronunciation": "/sɒŋ/", "meaning": "गीत", "english_sentence": "I like this song.", "native_sentence": "मलाई यो गीत मन पर्छ।", "synonym": "Tune"},
  {"word": "Dance", "pronunciation": "/dæns/", "meaning": "नाच", "english_sentence": "Can you dance?", "native_sentence": "के तपाईं नाच्न सक्नुहुन्छ?", "synonym": "Boogie"},
  {"word": "Football", "pronunciation": "/ˈfʊtbɔːl/", "meaning": "फुटबल", "english_sentence": "He plays football.", "native_sentence": "उनी फुटबल खेल्छन्।", "synonym": "Soccer"},
  {"word": "Game", "pronunciation": "/ɡeɪm/", "meaning": "खेल", "english_sentence": "I like this game.", "native_sentence": "मलाई यो खेल मन पर्छ।", "synonym": "Match"},
  {"word": "Ball", "pronunciation": "/bɔːl/", "meaning": "बल", "english_sentence": "Throw the ball.", "native_sentence": "बल फाल्नुहोस्।", "synonym": "Sphere"},
  {"word": "Team", "pronunciation": "/tiːm/", "meaning": "टोली", "english_sentence": "Our team is strong.", "native_sentence": "हाम्रो टोली बलियो छ।", "synonym": "Group"},
  {"word": "Race", "pronunciation": "/reɪs/", "meaning": "दौड", "english_sentence": "He won the race.", "native_sentence": "उनले दौड जिते।", "synonym": "Sprint"},
  {"word": "Exercise", "pronunciation": "/ˈeksərsaɪz/", "meaning": "व्यायाम", "english_sentence": "Exercise daily.", "native_sentence": "दिनहुँ व्यायाम गर्नुहोस्।", "synonym": "Workout"},
  {"word": "Healthy", "pronunciation": "/ˈhelθi/", "meaning": "स्वस्थ", "english_sentence": "Eat healthy food.", "native_sentence": "स्वस्थ खाना खानुहोस्।", "synonym": "Fit"},
  {"word": "Power", "pronunciation": "/ˈpaʊər/", "meaning": "शक्ति", "english_sentence": "Knowledge is power.", "native_sentence": "ज्ञान नै शक्ति हो।", "synonym": "Strength"},
  {"word": "Internet", "pronunciation": "/ˈɪntərnet/", "meaning": "इन्टरनेट", "english_sentence": "The internet is slow.", "native_sentence": "इन्टरनेट ढिलो छ।", "synonym": "Web"},
  {"word": "Email", "pronunciation": "/ˈiːmeɪl/", "meaning": "इमेल", "english_sentence": "Send me an email.", "native_sentence": "मलाई इमेल पठाउनुहोस्।", "synonym": "Message"},
  {"word": "Website", "pronunciation": "/ˈwebsaɪt/", "meaning": "वेबसाइट", "english_sentence": "Visit our website.", "native_sentence": "हाम्रो वेबसाइट हेर्नुहोस्।", "synonym": "Site"},
  {"word": "Password", "pronunciation": "/ˈpæswɜːrd/", "meaning": "पासवर्ड", "english_sentence": "Keep your password safe.", "native_sentence": "आफ्नो पासवर्ड सुरक्षित राख्नुहोस्।", "synonym": "Code"},
  {"word": "Video", "pronunciation": "/ˈvɪdioʊ/", "meaning": "भिडियो", "english_sentence": "Watch this video.", "native_sentence": "यो भिडियो हेर्नुहोस्।", "synonym": "Clip"},
  {"word": "Photo", "pronunciation": "/ˈfoʊtoʊ/", "meaning": "फोटो", "english_sentence": "This is a nice photo.", "native_sentence": "यो राम्रो फोटो हो।", "synonym": "Image"},
  {"word": "Message", "pronunciation": "/ˈmesɪdʒ/", "meaning": "सन्देश", "english_sentence": "I got your message.", "native_sentence": "मैले तिम्रो सन्देश पाएँ।", "synonym": "Note"},
  {"word": "Call", "pronunciation": "/kɔːl/", "meaning": "कल (फोन)", "english_sentence": "Give me a call.", "native_sentence": "मलाई कल गर्नुहोस्।", "synonym": "Ring"},
  {"word": "Noise", "pronunciation": "/nɔɪz/", "meaning": "हल्ला", "english_sentence": "Stop making noise.", "native_sentence": "हल्ला गर्न बन्द गर्नुहोस्।", "synonym": "Din"},
  {"word": "Quiet", "pronunciation": "/ˈkwaɪət/", "meaning": "शान्त", "english_sentence": "The library is quiet.", "native_sentence": "पुस्तकालय शान्त छ।", "synonym": "Silent"},
  {"word": "Talk", "pronunciation": "/tɔːk/", "meaning": "कुरा गर्नु", "english_sentence": "We need to talk.", "native_sentence": "हामीले कुरा गर्नुपर्छ।", "synonym": "Speak"},
  {"word": "Listen", "pronunciation": "/ˈlɪsn/", "meaning": "सुन्नु", "english_sentence": "Listen to the teacher.", "native_sentence": "शिक्षकको कुरा सुन्नुहोस्।", "synonym": "Hear"},
  {"word": "Care", "pronunciation": "/keər/", "meaning": "हेरचाह", "english_sentence": "Take care of yourself.", "native_sentence": "आफ्नो हेरचाह गर्नुहोस्।", "synonym": "Attention"},
  {"word": "Respect", "pronunciation": "/rɪˈspekt/", "meaning": "आदर", "english_sentence": "Respect your elders.", "native_sentence": "आफ्ना ठूलालाई आदर गर्नुहोस्।", "synonym": "Honor"},
  {"word": "Kindness", "pronunciation": "/ˈkaɪndnəs/", "meaning": "दया", "english_sentence": "Kindness is a virtue.", "native_sentence": "दया एउटा गुण हो।", "synonym": "Goodness"},
  {"word": "Family", "pronunciation": "/ˈfæmɪli/", "meaning": "परिवार", "english_sentence": "I love my family.", "native_sentence": "म मेरो परिवारलाई माया गर्छु।", "synonym": "Kin"},
  {"word": "Neighbor", "pronunciation": "/ˈneɪbər/", "meaning": "छिमेकी", "english_sentence": "My neighbor is helpful.", "native_sentence": "मेरो छिमेकी सहयोगी छ।", "synonym": "Nearby person"},
  {"word": "Guest", "pronunciation": "/ɡest/", "meaning": "पाहुना", "english_sentence": "The guest is here.", "native_sentence": "पाहुना यहाँ हुनुहुन्छ।", "synonym": "Visitor"},
  {"word": "Party", "pronunciation": "/ˈpɑːrti/", "meaning": "पार्टी (भोज)", "english_sentence": "Let's go to the party.", "native_sentence": "पार्टीमा जाऔं।", "synonym": "Celebration"},
  {"word": "Holiday", "pronunciation": "/ˈhɒlədeɪ/", "meaning": "बिदा", "english_sentence": "Today is a holiday.", "native_sentence": "आज बिदा हो।", "synonym": "Vacation"},
  {"word": "Journey", "pronunciation": "/ˈdʒɜːrni/", "meaning": "यात्रा", "english_sentence": "The journey was long.", "native_sentence": "यात्रा लामो थियो।", "synonym": "Trip"},
  {"word": "Safety", "pronunciation": "/ˈseɪfti/", "meaning": "सुरक्षा", "english_sentence": "Safety comes first.", "native_sentence": "सुरक्षा पहिले आउँछ।", "synonym": "Protection"},
  {"word": "Lucky", "pronunciation": "/ˈlʌki/", "meaning": "भाग्यमानी", "english_sentence": "You are very lucky.", "native_sentence": "तपाईं धेरै भाग्यमानी हुनुहुन्छ।", "synonym": "Fortunate"},
  {"word": "Special", "pronunciation": "/ˈspeʃl/", "meaning": "विशेष", "english_sentence": "Today is a special day.", "native_sentence": "आज एक विशेष दिन हो।", "synonym": "Unique"},
  {"word": "Simple", "pronunciation": "/ˈsɪmpl/", "meaning": "साधारण", "english_sentence": "It is a simple question.", "native_sentence": "यो एक साधारण प्रश्न हो।", "synonym": "Easy"},
  {"word": "Modern", "pronunciation": "/ˈmɒdərn/", "meaning": "आधुनिक", "english_sentence": "This is a modern house.", "native_sentence": "यो एक आधुनिक घर हो।", "synonym": "New"},
  {"word": "Boring", "pronunciation": "/ˈbɔːrɪŋ/", "meaning": "अल्छीलाग्दो", "english_sentence": "The movie was boring.", "native_sentence": "चलचित्र अल्छीलाग्दो थियो।", "synonym": "Dull"},
  {"word": "Exciting", "pronunciation": "/ɪkˈsaाइtɪŋ/", "meaning": "उत्साहजनक", "english_sentence": "The match was exciting.", "native_sentence": "खेल उत्साहजनक थियो।", "synonym": "Thrilling"},
  {"word": "Smart", "pronunciation": "/smɑːrt/", "meaning": "चलाख", "english_sentence": "He is a smart boy.", "native_sentence": "उनी चलाख केटो हुन्।", "synonym": "Clever"},
  {"word": "Lazy", "pronunciation": "/ˈleɪzi/", "meaning": "अल्छी", "english_sentence": "Don't be lazy.", "native_sentence": "अल्छी नबन्नुहोस्।", "synonym": "Idle"},
  {"word": "Busy", "pronunciation": "/ˈbɪzi/", "meaning": "व्यस्त", "english_sentence": "I am busy today.", "native_sentence": "म आज व्यस्त छु।", "synonym": "Active"},
  {"word": "Chilly", "pronunciation": "/ˈtʃɪli/", "meaning": "चिसो", "english_sentence": "The morning is chilly.", "native_sentence": "बिहान चिसो छ।", "synonym": "Cold"},
  {"word": "Taste", "pronunciation": "/teɪst/", "meaning": "स्वाद", "english_sentence": "The food has a good taste.", "native_sentence": "खानाको स्वाद राम्रो छ।", "synonym": "Flavor"},
  {"word": "Smell", "pronunciation": "/smel/", "meaning": "गन्ध", "english_sentence": "I like the smell of flowers.", "native_sentence": "मलाई फूलको गन्ध मन पर्छ।", "synonym": "Scent"},
  {"word": "Touch", "pronunciation": "/tʌtʃ/", "meaning": "छुनु", "english_sentence": "Don't touch the wire.", "native_sentence": "तार नछुनुहोस्।", "synonym": "Contact"},
  {"word": "Sunny", "pronunciation": "/ˈsʌni/", "meaning": "घमाइलो", "english_sentence": "It is a sunny day.", "native_sentence": "यो घमाइलो दिन हो।", "synonym": "Bright"},
  {"word": "Cloudy", "pronunciation": "/ˈklaʊdi/", "meaning": "बादल लागेको", "english_sentence": "The sky is cloudy.", "native_sentence": "आकाशमा बादल लागेको छ।", "synonym": "Overcast"},
  {"word": "Foggy", "pronunciation": "/ˈfɒɡi/", "meaning": "कुहिरो लागेको", "english_sentence": "It is foggy this morning.", "native_sentence": "आज बिहान कुहिरो लागेको छ।", "synonym": "Misty"},
  {"word": "Windy", "pronunciation": "/ˈwɪndi/", "meaning": "हुरी चल्ने", "english_sentence": "It is a windy afternoon.", "native_sentence": "यो एउटा हुरी चल्ने दिउँसो हो।", "synonym": "Breezy"},
  {"word": "Snow", "pronunciation": "/snoʊ/", "meaning": "हिउँ", "english_sentence": "I like to play in the snow.", "native_sentence": "मलाई हिउँमा खेल्न मन पर्छ।", "synonym": "Frost"},
  {"word": "East", "pronunciation": "/iːst/", "meaning": "पूर्व", "english_sentence": "The sun rises in the east.", "native_sentence": "घाम पूर्वबाट उदाउँछ।", "synonym": "Orient"},
  {"word": "West", "pronunciation": "/west/", "meaning": "पश्चिम", "english_sentence": "The sun sets in the west.", "native_sentence": "घाम पश्चिममा अस्ताउँछ।", "synonym": "Occident"},
  {"word": "North", "pronunciation": "/nɔːrθ/", "meaning": "उत्तर", "english_sentence": "The mountains are in the north.", "native_sentence": "पहाडहरू उत्तरमा छन्।", "synonym": "Arctic"},
  {"word": "South", "pronunciation": "/saʊθ/", "meaning": "दक्षिण", "english_sentence": "Birds fly to the south.", "native_sentence": "चराहरू दक्षिणतिर उड्छन्।", "synonym": "Austral"},
  {"word": "Up", "pronunciation": "/ʌp/", "meaning": "माथि", "english_sentence": "Look up at the sky.", "native_sentence": "आकाशतिर माथि हेर्नुहोस्।", "synonym": "Above"},
  {"word": "Down", "pronunciation": "/daʊn/", "meaning": "तल", "english_sentence": "Sit down on the floor.", "native_sentence": "भुइँमा तल बस्नुहोस्।", "synonym": "Below"},
  {"word": "Inside", "pronunciation": "/ˌɪnˈsaɪd/", "meaning": "भित्र", "english_sentence": "Come inside the house.", "native_sentence": "घरभित्र आउनुहोस्।", "synonym": "Within"},
  {"word": "Outside", "pronunciation": "/ˌaʊtˈsaɪd/", "meaning": "बाहिर", "english_sentence": "It is cold outside.", "native_sentence": "बाहिर चिसो छ।", "synonym": "Exterior"},
  {"word": "Near", "pronunciation": "/nɪər/", "meaning": "नजिक", "english_sentence": "The shop is near my house.", "native_sentence": "पसल मेरो घर नजिक छ।", "synonym": "Close"},
  {"word": "Far", "pronunciation": "/fɑːr/", "meaning": "टाढा", "english_sentence": "The school is very far.", "native_sentence": "विद्यालय धेरै टाढा छ।", "synonym": "Distant"},
  {"word": "Front", "pronunciation": "/frʌnt/", "meaning": "अगाडि", "english_sentence": "Stand in front of me.", "native_sentence": "मेरो अगाडि उभिनुहोस्।", "synonym": "Forward"},
  {"word": "Top", "pronunciation": "/tɒp/", "meaning": "टुप्पो (माथिल्लो भाग)", "english_sentence": "The book is on the top shelf.", "native_sentence": "किताब माथिल्लो तख्तामा छ।", "synonym": "Peak"},
  {"word": "Bottom", "pronunciation": "/ˈbɒtəm/", "meaning": "तलको भाग", "english_sentence": "The answer is at the bottom.", "native_sentence": "उत्तर तलको भागमा छ।", "synonym": "Base"},
  {"word": "Between", "pronunciation": "/bɪˈtwiːn/", "meaning": "बीचमा", "english_sentence": "Stand between your parents.", "native_sentence": "आफ्नो आमाबाबुको बीचमा उभिनुहोस्।", "synonym": "Amid"},
  {"word": "Wake up", "pronunciation": "/weɪk ʌp/", "meaning": "ब्यूँझनु", "english_sentence": "I wake up early.", "native_sentence": "म छिटो ब्यूँझन्छु।", "synonym": "Arise"},
  {"word": "Wash", "pronunciation": "/wɒʃ/", "meaning": "धुनु", "english_sentence": "Wash your face.", "native_sentence": "आफ्नो अनुहार धुनुहोस्।", "synonym": "Cleanse"},
  {"word": "Brush", "pronunciation": "/brʌʃ/", "meaning": "माझ्नु (ब्रश गर्नु)", "english_sentence": "Brush your teeth.", "native_sentence": "आफ्नो दाँत माझ्नुहोस्।", "synonym": "Sweep"},
  {"word": "Comb", "pronunciation": "/koʊm/", "meaning": "कोर्नु", "english_sentence": "Comb your hair.", "native_sentence": "आफ्नो कपाल कोर्नुहोस्।", "synonym": "Groom"},
  {"word": "Dress", "pronunciation": "/dres/", "meaning": "लुगा लगाउनु", "english_sentence": "Get dressed quickly.", "native_sentence": "छिटो लुगा लगाउनुहोस्।", "synonym": "Clothe"},
  {"word": "Drive", "pronunciation": "/draɪv/", "meaning": "चलाउनु (सवारी)", "english_sentence": "He can drive a car.", "native_sentence": "उनी गाडी चलाउन सक्छन्।", "synonym": "Steer"},
  {"word": "Ride", "pronunciation": "/raɪd/", "meaning": "चढ्नु (साइकल/घोडा)", "english_sentence": "I ride a bicycle.", "native_sentence": "म साइकल चढ्छु।", "synonym": "Travel"},
  {"word": "Push", "pronunciation": "/pʊʃ/", "meaning": "धकेल्नु", "english_sentence": "Push the door open.", "native_sentence": "ढोका धकेलेर खोल्नुहोस्।", "synonym": "Shove"},
  {"word": "Pull", "pronunciation": "/pʊl/", "meaning": "तान्नु", "english_sentence": "Pull the rope.", "native_sentence": "डोरी तान्नुहोस्।", "synonym": "Drag"},
  {"word": "Carry", "pronunciation": "/ˈkæri/", "meaning": "बोक्नु", "english_sentence": "Carry this bag.", "native_sentence": "यो झोला बोक्नुहोस्।", "synonym": "Hold"},
  {"word": "Hold", "pronunciation": "/hoʊld/", "meaning": "समात्नु", "english_sentence": "Hold my hand.", "native_sentence": "मेरो हात समात्नुहोस्।", "synonym": "Grasp"},
  {"word": "Drop", "pronunciation": "/drɒp/", "meaning": "खसाल्नु", "english_sentence": "Don't drop the glass.", "native_sentence": "ग्लास नखसाल्नुहोस्।", "synonym": "Fall"},
  {"word": "Choose", "pronunciation": "/tʃuːz/", "meaning": "छान्नु", "english_sentence": "Choose one color.", "native_sentence": "एउटा रंग छान्नुहोस्।", "synonym": "Select"},
  {"word": "Pay", "pronunciation": "/peɪ/", "meaning": "तिर्नु", "english_sentence": "Pay the bill.", "native_sentence": "बिल तिर्नुहोस्।", "synonym": "Settle"},
  {"word": "Show", "pronunciation": "/ʃoʊ/", "meaning": "देखाउनु", "english_sentence": "Show me your book.", "native_sentence": "मलाई आफ्नो किताब देखाउनुहोस्।", "synonym": "Display"},
  {"word": "Hide", "pronunciation": "/haɪd/", "meaning": "लुक्नु", "english_sentence": "Where did he hide?", "native_sentence": "उनी कहाँ लुके?", "synonym": "Conceal"},
  {"word": "Break", "pronunciation": "/breɪk/", "meaning": "भाँच्नु (फुटाउनु)", "english_sentence": "Don't break the toy.", "native_sentence": "खेलौना नफुटाउनुहोस्।", "synonym": "Fracture"},
  {"word": "Fix", "pronunciation": "/fɪks/", "meaning": "मर्मत गर्नु", "english_sentence": "Can you fix this?", "native_sentence": "के तपाईं यसलाई मर्मत गर्न सक्नुहुन्छ?", "synonym": "Repair"},
  {"word": "True", "pronunciation": "/truː/", "meaning": "साँचो", "english_sentence": "This story is true.", "native_sentence": "यो कथा साँचो हो।", "synonym": "Correct"},
  {"word": "False", "pronunciation": "/fɔːls/", "meaning": "झूटो", "english_sentence": "It is a false statement.", "native_sentence": "यो झूटो बयान हो।", "synonym": "Wrong"},
  {"word": "Early", "pronunciation": "/ˈɜːrli/", "meaning": "चाँडै", "english_sentence": "Come to school early.", "native_sentence": "विद्यालय चाँडै आउनुहोस्।", "synonym": "Soon"},
  {"word": "Late", "pronunciation": "/leɪt/", "meaning": "ढिलो", "english_sentence": "Don't be late for class.", "native_sentence": "कक्षाको लागि ढिलो नगर्नुहोस्।", "synonym": "Overdue"},
  {"word": "First", "pronunciation": "/fɜːrst/", "meaning": "पहिलो", "english_sentence": "He came first in class.", "native_sentence": "उनी कक्षामा पहिलो भए।", "synonym": "Initial"},
  {"word": "Last", "pronunciation": "/læst/", "meaning": "अन्तिम", "english_sentence": "This is the last bus.", "native_sentence": "यो अन्तिम bus हो।", "synonym": "Final"},
  {"word": "Together", "pronunciation": "/təˈɡeðər/", "meaning": "सँगै", "english_sentence": "Let's work together.", "native_sentence": "सँगै काम गरौं।", "synonym": "Combined"},
  {"word": "Alone", "pronunciation": "/əˈloʊn/", "meaning": "एक्लै", "english_sentence": "She is sitting alone.", "native_sentence": "उनी एक्लै बसिरहेकी छिन्।", "synonym": "Solitary"},
  {"word": "Dust", "pronunciation": "/dʌst/", "meaning": "धुलो", "english_sentence": "Clean the dust from the table.", "native_sentence": "टेबलबाट धुलो सफा गर्नुहोस्।", "synonym": "Powder"},
  {"word": "Smoke", "pronunciation": "/smoʊk/", "meaning": "धुवाँ", "english_sentence": "Smoke is coming out.", "native_sentence": "धुवाँ निस्किरहेको छ।", "synonym": "Fume"},
  {"word": "Fire", "pronunciation": "/ˈfaɪər/", "meaning": "आगो", "english_sentence": "Don't play with fire.", "native_sentence": "आगोसँग नखेल्नुहोस्।", "synonym": "Flame"},
  {"word": "Ice", "pronunciation": "/aɪs/", "meaning": "हिउँ/बरफ", "english_sentence": "The water turned into ice.", "native_sentence": "पानी बरफमा परिणत भयो।", "synonym": "Frost"},
  {"word": "Cold", "pronunciation": "/koʊld/", "meaning": "चिसो", "english_sentence": "Today is very cold.", "native_sentence": "आज धेरै चिसो छ।", "synonym": "Chilly"},
  {"word": "Warm", "pronunciation": "/wɔːrm/", "meaning": "न्यानो", "english_sentence": "Wear warm clothes.", "native_sentence": "न्यानो लुगा लगाउनुहोस्।", "synonym": "Toasty"},
  {"word": "Brother", "pronunciation": "/ˈbrʌðər/", "meaning": "दाजु/भाइ", "english_sentence": "My brother is helpful.", "native_sentence": "मेरो भाइ सहयोगी छ।", "synonym": "Sibling"},
  {"word": "Sister", "pronunciation": "/ˈsɪstər/", "meaning": "दिदी/बहिनी", "english_sentence": "I have one sister.", "native_sentence": "मेरो एउटी बहिनी छ।", "synonym": "Sibling"},
  {"word": "Uncle", "pronunciation": "/ˈʌŋkl/", "meaning": "काका/मामा", "english_sentence": "My uncle lives in Pokhara.", "native_sentence": "मेरो मामा पोखरामा बस्नुहुन्छ।", "synonym": "Relative"},
  {"word": "Aunt", "pronunciation": "/ænt/", "meaning": "काकी/माइजु", "english_sentence": "My aunt is a teacher.", "native_sentence": "मेरो काकी शिक्षक हुनुहुन्छ।", "synonym": "Relative"},
  {"word": "Baby", "pronunciation": "/ˈbeɪbi/", "meaning": "बच्चा", "english_sentence": "The baby is laughing.", "native_sentence": "बच्चा हाँसिरहेको छ।", "synonym": "Infant"},
  {"word": "Man", "pronunciation": "/mæn/", "meaning": "मानिस (पुरुष)", "english_sentence": "He is a tall man.", "native_sentence": "उनी एक अग्लो मानिस हुन्।", "synonym": "Male"},
  {"word": "Woman", "pronunciation": "/ˈwʊmən/", "meaning": "महिला", "english_sentence": "The woman is singing.", "native_sentence": "महिला गाइरहेकी छिन्।", "synonym": "Female"},
  {"word": "Neck", "pronunciation": "/nek/", "meaning": "घाँटी", "english_sentence": "She wears a scarf on her neck.", "native_sentence": "उनले आफ्नो घाँटीमा स्कार्फ लगाउँछिन्।", "synonym": "Nape"},
  {"word": "Back", "pronunciation": "/bæk/", "meaning": "ढाड", "english_sentence": "Sit with a straight back.", "native_sentence": "सिधा ढाड गरेर बस्नुहोस्।", "synonym": "Rear"},
  {"word": "Blood", "pronunciation": "/blʌd/", "meaning": "रगत", "english_sentence": "Blood is red.", "native_sentence": "रगत रातो हुन्छ।", "synonym": "Gore"},
  {"word": "Bone", "pronunciation": "/boʊn/", "meaning": "हड्डी", "english_sentence": "The dog has a bone.", "native_sentence": "कुकुरसँग हड्डी छ।", "synonym": "Skeletal"},
  {"word": "Skin", "pronunciation": "/skɪn/", "meaning": "छाला", "english_sentence": "Protect your skin from sun.", "native_sentence": "आफ्नो छालालाई घामबाट बचाउनुहोस्।", "synonym": "Surface"},
  {"word": "Tea", "pronunciation": "/tiː/", "meaning": "चिया", "english_sentence": "I like hot tea.", "native_sentence": "मलाई तातो चिया मन पर्छ।", "synonym": "Brew"},
  {"word": "Coffee", "pronunciation": "/ˈkɒfi/", "meaning": "कफी", "english_sentence": "Do you want coffee?", "native_sentence": "के तपाईलाई कफी चाहिन्छ?", "synonym": "Java"},
  {"word": "Meat", "pronunciation": "/miːt/", "meaning": "मासु", "english_sentence": "He does not eat meat.", "native_sentence": "उनी मासु खाँदैनन्।", "synonym": "Flesh"},
  {"word": "Rice", "pronunciation": "/raɪs/", "meaning": "चामल/भात", "english_sentence": "We eat rice daily.", "native_sentence": "हामी दिनहुँ भात खान्छौं।", "synonym": "Grain"},
  {"word": "Oil", "pronunciation": "/ɔɪl/", "meaning": "तेल", "english_sentence": "Use less oil in food.", "native_sentence": "खाना मा कम तेल प्रयोग गर्नुहोस्।", "synonym": "Fat"},
  {"word": "Soap", "pronunciation": "/soʊp/", "meaning": "साबुन", "english_sentence": "Wash with soap.", "native_sentence": "साबुनले धुनुहोस्।", "synonym": "Cleaner"},
  {"word": "Towel", "pronunciation": "/ˈtaʊəl/", "meaning": "तौलिया", "english_sentence": "Dry yourself with a towel.", "native_sentence": "आफुलाई तौलियाले सुकाउनुहोस्।", "synonym": "Cloth"},
  {"word": "Key", "pronunciation": "/kiː/", "meaning": "साँचो", "english_sentence": "Where is the door key?", "native_sentence": "ढोकाको साँचो कहाँ छ?", "synonym": "Opener"},
  {"word": "Lock", "pronunciation": "/lɒk/", "meaning": "ताल्चा", "english_sentence": "The lock is broken.", "native_sentence": "ताल्चा फुटेको छ।", "synonym": "Latch"},
  {"word": "Clock", "pronunciation": "/klɒk/", "meaning": "घडी", "english_sentence": "The clock shows 10 AM.", "native_sentence": "घडीले बिहानको १० बजेको देखाउँछ।", "synonym": "Timer"},
  {"word": "Watch", "pronunciation": "/wɒtʃ/", "meaning": "हाते घडी", "english_sentence": "I have a gold watch.", "native_sentence": "मसँग सुनको घडी छ।", "synonym": "Timepiece"},
  {"word": "Hat", "pronunciation": "/hæt/", "meaning": "टोपी", "english_sentence": "Wear a hat in the sun.", "native_sentence": "घाममा टोपी लगाउनुहोस्।", "synonym": "Cap"},
  {"word": "Umbrella", "pronunciation": "/ʌmˈbrelə/", "meaning": "छाता", "english_sentence": "Take an umbrella in rain.", "native_sentence": "झरीमा छाता लिनुहोस्।", "synonym": "Parasol"},
  {"word": "Star", "pronunciation": "/stɑːr/", "meaning": "तारा", "english_sentence": "I see a bright star.", "native_sentence": "म एउटा चम्किलो तारा देख्छु।", "synonym": "Astro"},
  {"word": "Moon", "pronunciation": "/muːn/", "meaning": "चन्द्रमा", "english_sentence": "The moon is white.", "native_sentence": "चन्द्रमा सेतो छ।", "synonym": "Luna"},
  {"word": "World", "pronunciation": "/wɜːrld/", "meaning": "संसार", "english_sentence": "The world is big.", "native_sentence": "संसार ठूलो छ।", "synonym": "Globe"},
  {"word": "Sea", "pronunciation": "/siː/", "meaning": "समुद्र", "english_sentence": "The sea water is salty.", "native_sentence": "समुद्रको पानी नुनिलो हुन्छ।", "synonym": "Ocean"},
  {"word": "Lake", "pronunciation": "/leɪk/", "meaning": "ताल", "english_sentence": "Phewa is a beautiful lake.", "native_sentence": "फेवा एउटा सुन्दर ताल हो।", "synonym": "Pond"},
  {"word": "Winter", "pronunciation": "/ˈwɪntər/", "meaning": "जाडो", "english_sentence": "It snows in winter.", "native_sentence": "जाडोमा हिउँ पर्छ।", "synonym": "Cold season"},
  {"word": "Summer", "pronunciation": "/ˈsʌmər/", "meaning": "गर्मी", "english_sentence": "I like ice cream in summer.", "native_sentence": "मलाई गर्मीमा आइसक्रिम मन पर्छ।", "synonym": "Heat"},
  {"word": "Silver", "pronunciation": "/ˈsɪlvər/", "meaning": "चाँदी", "english_sentence": "The coin is made of silver.", "native_sentence": "सिक्का चाँदीले बनेको छ।", "synonym": "Argent"},
  {"word": "Black", "pronunciation": "/blæk/", "meaning": "कालो", "english_sentence": "I have a black pen.", "native_sentence": "मसँग कालो कलम छ।", "synonym": "Dark"},
  {"word": "White", "pronunciation": "/waɪt/", "meaning": "सेतो", "english_sentence": "The milk is white.", "native_sentence": "दूध सेतो छ।", "synonym": "Pale"},
  {"word": "Red", "pronunciation": "/red/", "meaning": "रातो", "english_sentence": "Red is my favorite color.", "native_sentence": "रातो मेरो मनपर्ने रंग हो।", "synonym": "Crimson"},
  {"word": "Blue", "pronunciation": "/bluː/", "meaning": "नीलो", "english_sentence": "The ocean is blue.", "native_sentence": "महासागर नीलो छ।", "synonym": "Azure"},
  {"word": "Green", "pronunciation": "/ɡriːn/", "meaning": "हरियो", "english_sentence": "The grass is green.", "native_sentence": "घाँस हरियो छ।", "synonym": "Verdant"},
  {"word": "Yellow", "pronunciation": "/ˈjeloʊ/", "meaning": "पहेलो", "english_sentence": "The banana is yellow.", "native_sentence": "केरा पहेलो छ।", "synonym": "Golden"}
];
