
export const BEGINNER_HINDI_DATA = [
  {"word": "Water", "pronunciation": "/ˈwɔːtər/", "meaning": "पानी", "english_sentence": "I drink water.", "native_sentence": "मैं पानी पीता हूँ।", "synonym": "Aqua", "language": "hindi"},
  {"word": "School", "pronunciation": "/skuːl/", "meaning": "विद्यालय", "english_sentence": "The school is big.", "native_sentence": "विद्यालय बड़ा है।", "synonym": "Academy", "language": "hindi"},
  {"word": "Book", "pronunciation": "/bʊk/", "meaning": "किताब", "english_sentence": "I read a book.", "native_sentence": "मैं किताब पढ़ता हूँ।", "synonym": "Volume", "language": "hindi"},
  {"word": "Friend", "pronunciation": "/frend/", "meaning": "मित्र", "english_sentence": "He is my friend.", "native_sentence": "वह मेरा मित्र है।", "synonym": "Buddy", "language": "hindi"},
  {"word": "House", "pronunciation": "/haʊs/", "meaning": "घर", "english_sentence": "My house is clean.", "native_sentence": "मेरा घर साफ है।", "synonym": "Home", "language": "hindi"},
  {"word": "Eat", "pronunciation": "/iːt/", "meaning": "खाना", "english_sentence": "I eat an apple.", "native_sentence": "मैं सेब खाता हूँ।", "synonym": "Consume", "language": "hindi"},
  {"word": "Sleep", "pronunciation": "/sliːp/", "meaning": "सोना", "english_sentence": "I sleep at night.", "native_sentence": "मैं रात में सोता हूँ।", "synonym": "Rest", "language": "hindi"},
  {"word": "Run", "pronunciation": "/rʌn/", "meaning": "दौड़ना", "english_sentence": "He can run fast.", "native_sentence": "वह तेज दौड़ सकता है।", "synonym": "Dash", "language": "hindi"},
  {"word": "Sun", "pronunciation": "/sʌn/", "meaning": "सूरज", "english_sentence": "The sun is hot.", "native_sentence": "सूरज गर्म होता है।", "synonym": "Sol", "language": "hindi"},
  {"word": "Sky", "pronunciation": "/skaɪ/", "meaning": "आकाश", "english_sentence": "The sky is blue.", "native_sentence": "आकाश नीला है।", "synonym": "Heavens", "language": "hindi"},
  {"word": "Tree", "pronunciation": "/triː/", "meaning": "पेड़", "english_sentence": "The tree is tall.", "native_sentence": "पेड़ ऊँचा है।", "synonym": "Plant", "language": "hindi"},
  {"word": "Flower", "pronunciation": "/ˈflaʊər/", "meaning": "फूल", "english_sentence": "This flower is beautiful.", "native_sentence": "यह फूल सुंदर है।", "synonym": "Bloom", "language": "hindi"},
  {"word": "Milk", "pronunciation": "/mɪlk/", "meaning": "दूध", "english_sentence": "Milk is good for health.", "native_sentence": "दूध स्वास्थ्य के लिए अच्छा है।", "synonym": "Dairy", "language": "hindi"},
  {"word": "Mother", "pronunciation": "/ˈmʌðər/", "meaning": "माँ", "english_sentence": "I love my mother.", "native_sentence": "मैं अपनी माँ से प्यार करता हूँ।", "synonym": "Mom", "language": "hindi"},
  {"word": "Father", "pronunciation": "/ˈfɑːðər/", "meaning": "पिता", "english_sentence": "My father is kind.", "native_sentence": "मेरे पिता दयालु हैं।", "synonym": "Dad", "language": "hindi"},
  {"word": "Bird", "pronunciation": "/bɜːrd/", "meaning": "पक्षी", "english_sentence": "The bird can fly.", "native_sentence": "पक्षी उड़ सकता है।", "synonym": "Fowl", "language": "hindi"},
  {"word": "Dog", "pronunciation": "/dɔːɡ/", "meaning": "कुत्ता", "english_sentence": "The dog is barking.", "native_sentence": "कुत्ता भौंक रहा है।", "synonym": "Canine", "language": "hindi"},
  {"word": "Cat", "pronunciation": "/kæt/", "meaning": "बिल्ली", "english_sentence": "The cat is sleeping.", "native_sentence": "बिल्ली सो रही है।", "synonym": "Feline", "language": "hindi"},
  {"word": "Fish", "pronunciation": "/fɪʃ/", "meaning": "मछली", "english_sentence": "The fish lives in water.", "native_sentence": "मछली पानी में रहती है।", "synonym": "Seafood", "language": "hindi"},
  {"word": "Road", "pronunciation": "/roʊd/", "meaning": "सड़क", "english_sentence": "The road is long.", "native_sentence": "सड़क लंबी है।", "synonym": "Street", "language": "hindi"},
  {"word": "Car", "pronunciation": "/kɑːr/", "meaning": "गाड़ी", "english_sentence": "I have a red car.", "native_sentence": "मेरे पास लाल गाड़ी है।", "synonym": "Vehicle", "language": "hindi"},
  {"word": "Apple", "pronunciation": "/ˈæpəl/", "meaning": "सेब", "english_sentence": "The apple is sweet.", "native_sentence": "सेब मीठा है।", "synonym": "Fruit", "language": "hindi"},
  {"word": "Pencil", "pronunciation": "/ˈpensəl/", "meaning": "पेंसिल", "english_sentence": "I write with a pencil.", "native_sentence": "मैं पेंसिल से लिखता हूँ।", "synonym": "Writer", "language": "hindi"},
  {"word": "Paper", "pronunciation": "/ˈpeɪpər/", "meaning": "कागज", "english_sentence": "Write on the paper.", "native_sentence": "कागज पर लिखो।", "synonym": "Sheet", "language": "hindi"},
  {"word": "Day", "pronunciation": "/deɪ/", "meaning": "दिन", "english_sentence": "It is a sunny day.", "native_sentence": "आज धूप वाला दिन है।", "synonym": "Daytime", "language": "hindi"},
  {"word": "Night", "pronunciation": "/naɪt/", "meaning": "रात", "english_sentence": "The stars shine at night.", "native_sentence": "रात में तारे चमकते हैं।", "synonym": "Darkness", "language": "hindi"},
  {"word": "Hand", "pronunciation": "/hænd/", "meaning": "हाथ", "english_sentence": "Wash your hand.", "native_sentence": "अपने हाथ धोओ।", "synonym": "Palm", "language": "hindi"},
  {"word": "Foot", "pronunciation": "/fʊt/", "meaning": "पैर", "english_sentence": "He hurt his foot.", "native_sentence": "उसके पैर में चोट लगी।", "synonym": "Paw", "language": "hindi"},
  {"word": "Eye", "pronunciation": "/aɪ/", "meaning": "आँख", "english_sentence": "Close your eye.", "native_sentence": "अपनी आँख बंद करो।", "synonym": "Optic", "language": "hindi"},
  {"word": "Ear", "pronunciation": "/ɪər/", "meaning": "कान", "english_sentence": "Listen with your ear.", "native_sentence": "अपने कान से सुनो।", "synonym": "Aural", "language": "hindi"},
  {"word": "Strong", "pronunciation": "/strɔːŋ/", "meaning": "मजबूत", "english_sentence": "He is very strong.", "native_sentence": "वह बहुत मजबूत है।", "synonym": "Powerful", "language": "hindi"},
  {"word": "Weak", "pronunciation": "/wiːk/", "meaning": "कमजोर", "english_sentence": "The bridge is weak.", "native_sentence": "पुल कमजोर है।", "synonym": "Fragile", "language": "hindi"},
  {"word": "New", "pronunciation": "/njuː/", "meaning": "नया", "english_sentence": "I bought a new shirt.", "native_sentence": "मैंने नई शर्ट खरीदी।", "synonym": "Fresh", "language": "hindi"},
  {"word": "Old", "pronunciation": "/oʊld/", "meaning": "पुराना", "english_sentence": "The book is old.", "native_sentence": "किताब पुरानी है।", "synonym": "Ancient", "language": "hindi"},
  {"word": "Rich", "pronunciation": "/rɪtʃ/", "meaning": "अमीर", "english_sentence": "He is a rich man.", "native_sentence": "वह एक अमीर आदमी है।", "synonym": "Wealthy", "language": "hindi"},
  {"word": "Poor", "pronunciation": "/pɔːr/", "meaning": "गरीब", "english_sentence": "Help the poor people.", "native_sentence": "गरीब लोगों की मदद करो।", "synonym": "Needy", "language": "hindi"},
  {"word": "Hot", "pronunciation": "/hɒt/", "meaning": "गरम", "english_sentence": "The tea is hot.", "native_sentence": "चाय गरम है।", "synonym": "Warm", "language": "hindi"},
  {"word": "Smile", "pronunciation": "/smaɪl/", "meaning": "मुस्कान", "english_sentence": "She has a nice smile.", "native_sentence": "उसकी मुस्कान अच्छी है।", "synonym": "Grin", "language": "hindi"},
  {"word": "Crying", "pronunciation": "/ˈkraɪɪŋ/", "meaning": "रोना", "english_sentence": "The baby is crying.", "native_sentence": "बच्चा रो रहा है।", "synonym": "Weeping", "language": "hindi"},
  {"word": "Laugh", "pronunciation": "/læf/", "meaning": "हँसना", "english_sentence": "We laugh together.", "native_sentence": "हम साथ में हँसते हैं।", "synonym": "Chuckle", "language": "hindi"},
  {"word": "Jump", "pronunciation": "/dʒʌmp/", "meaning": "कूदना", "english_sentence": "Kids like to jump.", "native_sentence": "बच्चों को कूदना पसंद है।", "synonym": "Leap", "language": "hindi"},
  {"word": "Small", "pronunciation": "/smɔːl/", "meaning": "छोटा", "english_sentence": "The ant is small.", "native_sentence": "चींटी छोटी होती है।", "synonym": "Tiny", "language": "hindi"},
  {"word": "Big", "pronunciation": "/bɪɡ/", "meaning": "बड़ा", "english_sentence": "That is a big elephant.", "native_sentence": "वह एक बड़ा हाथी है।", "synonym": "Huge", "language": "hindi"},
  {"word": "Play", "pronunciation": "/pleɪ/", "meaning": "खेलना", "english_sentence": "Let's play football.", "native_sentence": "चलो फुटबॉल खेलते हैं।", "synonym": "Sport", "language": "hindi"},
  {"word": "Work", "pronunciation": "/wɜːrk/", "meaning": "काम", "english_sentence": "He goes to work.", "native_sentence": "वह काम पर जाता है।", "synonym": "Job", "language": "hindi"},
  {"word": "Stop", "pronunciation": "/stɒp/", "meaning": "रोकना", "english_sentence": "Stop the car here.", "native_sentence": "यहाँ गाड़ी रोको।", "synonym": "Halt", "language": "hindi"},
  {"word": "Slow", "pronunciation": "/sloʊ/", "meaning": "धीमा", "english_sentence": "The turtle is slow.", "native_sentence": "कछुआ धीमा होता है।", "synonym": "Leisurely", "language": "hindi"},
  {"word": "Quick", "pronunciation": "/kwɪk/", "meaning": "तेज", "english_sentence": "Be quick, we are late.", "native_sentence": "जल्दी करो, हम देर हो रहे हैं।", "synonym": "Rapid", "language": "hindi"},
  {"word": "Happy", "pronunciation": "/ˈhæpi/", "meaning": "खुश", "english_sentence": "I am very happy.", "native_sentence": "मैं बहुत खुश हूँ।", "synonym": "Cheerful", "language": "hindi"},
  {"word": "Sad", "pronunciation": "/sæd/", "meaning": "दुखी", "english_sentence": "Don't be sad.", "native_sentence": "दुखी मत हो।", "synonym": "Unhappy", "language": "hindi"},
  {"word": "Door", "pronunciation": "/dɔːr/", "meaning": "दरवाज़ा", "english_sentence": "Open the door.", "native_sentence": "दरवाज़ा खोलिए।", "synonym": "Entrance", "language": "hindi"},
  {"word": "Window", "pronunciation": "/ˈwɪndoʊ/", "meaning": "खिड़की", "english_sentence": "Close the window.", "native_sentence": "खिड़की बंद कीजिए।", "synonym": "Opening", "language": "hindi"},
  {"word": "Chair", "pronunciation": "/tʃeər/", "meaning": "कुर्सी", "english_sentence": "Sit on the chair.", "native_sentence": "कुर्सी पर बैठिए।", "synonym": "Seat", "language": "hindi"},
  {"word": "Table", "pronunciation": "/ˈteɪbəl/", "meaning": "मेज़", "english_sentence": "Put it on the table.", "native_sentence": "इसे मेज़ पर रखिए।", "synonym": "Desk", "language": "hindi"},
  {"word": "Bed", "pronunciation": "/bed/", "meaning": "बिस्तर", "english_sentence": "The bed is soft.", "native_sentence": "बिस्तर नरम है।", "synonym": "Couch", "language": "hindi"},
  {"word": "Knife", "pronunciation": "/naɪf/", "meaning": "चाकू", "english_sentence": "Be careful with the knife.", "native_sentence": "चाकू से सावधान रहिए।", "synonym": "Blade", "language": "hindi"},
  {"word": "Spoon", "pronunciation": "/spuːn/", "meaning": "चम्मच", "english_sentence": "I eat with a spoon.", "native_sentence": "मैं चम्मच से खाता हूँ।", "synonym": "Scoop", "language": "hindi"},
  {"word": "Plate", "pronunciation": "/pleɪt/", "meaning": "थाली", "english_sentence": "The plate is empty.", "native_sentence": "थाली खाली है।", "synonym": "Dish", "language": "hindi"},
  {"word": "Shirt", "pronunciation": "/ʃɜːrt/", "meaning": "कमीज़", "english_sentence": "Your shirt is blue.", "native_sentence": "तुम्हारी कमीज़ नीली है।", "synonym": "Top", "language": "hindi"},
  {"word": "Shoes", "pronunciation": "/ʃuːz/", "meaning": "जूते", "english_sentence": "Put on your shoes.", "native_sentence": "अपने जूते पहनिए।", "synonym": "Footwear", "language": "hindi"},
  {"word": "Bag", "pronunciation": "/bæɡ/", "meaning": "बैग", "english_sentence": "Carry your bag.", "native_sentence": "अपना बैग उठाइए।", "synonym": "Sack", "language": "hindi"},
  {"word": "Face", "pronunciation": "/feɪs/", "meaning": "चेहरा", "english_sentence": "Wash your face.", "native_sentence": "अपना चेहरा धोइए।", "synonym": "Countenance", "language": "hindi"},
  {"word": "Hair", "pronunciation": "/heər/", "meaning": "बाल", "english_sentence": "She has long hair.", "native_sentence": "उसके बाल लंबे हैं।", "synonym": "Locks", "language": "hindi"},
  {"word": "Tooth", "pronunciation": "/tuːθ/", "meaning": "दाँत", "english_sentence": "Brush your tooth.", "native_sentence": "अपने दाँत साफ़ कीजिए।", "synonym": "Ivory", "language": "hindi"},
  {"word": "Nose", "pronunciation": "/noʊz/", "meaning": "नाक", "english_sentence": "Breathe through your nose.", "native_sentence": "नाक से साँस लीजिए।", "synonym": "Snout", "language": "hindi"},
  {"word": "River", "pronunciation": "/ˈrɪvər/", "meaning": "नदी", "english_sentence": "The river is deep.", "native_sentence": "नदी गहरी है।", "synonym": "Stream", "language": "hindi"},
  {"word": "Mountain", "pronunciation": "/ˈmaʊntən/", "meaning": "पहाड़", "english_sentence": "The mountain is high.", "native_sentence": "पहाड़ ऊँचा है।", "synonym": "Peak", "language": "hindi"},
  {"word": "Rain", "pronunciation": "/reɪn/", "meaning": "बारिश", "english_sentence": "I like the rain.", "native_sentence": "मुझे बारिश पसंद है।", "synonym": "Shower", "language": "hindi"},
  {"word": "Wind", "pronunciation": "/wɪnd/", "meaning": "हवा", "english_sentence": "The wind is cold.", "native_sentence": "हवा ठंडी है।", "synonym": "Breeze", "language": "hindi"},
  {"word": "Cloud", "pronunciation": "/klaʊd/", "meaning": "बादल", "english_sentence": "There are white clouds.", "native_sentence": "आसमान में सफ़ेद बादल हैं।", "synonym": "Mist", "language": "hindi"},
  {"word": "Stone", "pronunciation": "/stoʊn/", "meaning": "पत्थर", "english_sentence": "Don't throw the stone.", "native_sentence": "पत्थर मत फेंकिए।", "synonym": "Rock", "language": "hindi"},
  {"word": "Grass", "pronunciation": "/ɡræs/", "meaning": "घास", "english_sentence": "Sit on the grass.", "native_sentence": "घास पर बैठिए।", "synonym": "Turf", "language": "hindi"},
  {"word": "Gold", "pronunciation": "/ɡoʊld/", "meaning": "सोना", "english_sentence": "Gold is expensive.", "native_sentence": "सोना महँगा होता है।", "synonym": "Aurum", "language": "hindi"},
  {"word": "Iron", "pronunciation": "/ˈaɪərn/", "meaning": "लोहा", "english_sentence": "Iron is a strong metal.", "native_sentence": "लोहा एक मज़बूत धातु है।", "synonym": "Steel", "language": "hindi"},
  {"word": "Bread", "pronunciation": "/bred/", "meaning": "रोटी", "english_sentence": "I like fresh bread.", "native_sentence": "मुझे ताज़ी रोटी पसंद है।", "synonym": "Loaf", "language": "hindi"},
  {"word": "Egg", "pronunciation": "/eɡ/", "meaning": "अंडा", "english_sentence": "I eat an egg daily.", "native_sentence": "मैं रोज़ एक अंडा खाता हूँ।", "synonym": "Ovum", "language": "hindi"},
  {"word": "Fruit", "pronunciation": "/fruːt/", "meaning": "फल", "english_sentence": "Eat more fruit.", "native_sentence": "ज़्यादा फल खाइए।", "synonym": "Produce", "language": "hindi"},
  {"word": "Vegetable", "pronunciation": "/ˈvedʒtəbəl/", "meaning": "सब्ज़ी", "english_sentence": "Buy some vegetables.", "native_sentence": "कुछ सब्ज़ियाँ खरीदिए।", "synonym": "Greens", "language": "hindi"},
  {"word": "Salt", "pronunciation": "/sɔːlt/", "meaning": "नमक", "english_sentence": "Add some salt.", "native_sentence": "थोड़ा नमक डालिए।", "synonym": "Sodium", "language": "hindi"},
  {"word": "Sugar", "pronunciation": "/ˈʃʊɡər/", "meaning": "चीनी", "english_sentence": "Sugar is sweet.", "native_sentence": "चीनी मीठी होती है।", "synonym": "Sweetener", "language": "hindi"},
  {"word": "Sweet", "pronunciation": "/swiːt/", "meaning": "मीठा", "english_sentence": "The cake is sweet.", "native_sentence": "केक मीठा है।", "synonym": "Sugary", "language": "hindi"},
  {"word": "Bitter", "pronunciation": "/ˈbɪtər/", "meaning": "कड़वा", "english_sentence": "This medicine is bitter.", "native_sentence": "यह दवा कड़वी है।", "synonym": "Acid", "language": "hindi"},
  {"word": "Open", "pronunciation": "/ˈoʊpən/", "meaning": "खोलना", "english_sentence": "Open your eyes.", "native_sentence": "अपनी आँखें खोलिए।", "synonym": "Unlock", "language": "hindi"},
  {"word": "Close", "pronunciation": "/kloʊz/", "meaning": "बंद करना", "english_sentence": "Close the book.", "native_sentence": "किताब बंद कीजिए।", "synonym": "Shut", "language": "hindi"},
  {"word": "Clean", "pronunciation": "/kliːn/", "meaning": "साफ़", "english_sentence": "Keep your hands clean.", "native_sentence": "अपने हाथ साफ़ रखिए।", "synonym": "Tidy", "language": "hindi"},
  {"word": "Dirty", "pronunciation": "/ˈdɜːrti/", "meaning": "गंदा", "english_sentence": "Your clothes are dirty.", "native_sentence": "तुम्हारी कपड़े गंदे हैं।", "synonym": "Filthy", "language": "hindi"},
  {"word": "Tall", "pronunciation": "/tɔːl/", "meaning": "लंबा", "english_sentence": "He is very tall.", "native_sentence": "वह बहुत लंबा है।", "synonym": "High", "language": "hindi"},
  {"word": "Short", "pronunciation": "/ʃɔːrt/", "meaning": "छोटा", "english_sentence": "The boy is short.", "native_sentence": "लड़का छोटा है।", "synonym": "Brief", "language": "hindi"},
  {"word": "Full", "pronunciation": "/fʊl/", "meaning": "भरा हुआ", "english_sentence": "The glass is full.", "native_sentence": "गिलास भरा हुआ है।", "synonym": "Packed", "language": "hindi"},
  {"word": "Empty", "pronunciation": "/ˈempti/", "meaning": "खाली", "english_sentence": "The box is empty.", "native_sentence": "डिब्बा खाली है।", "synonym": "Vacant", "language": "hindi"},
  {"word": "Hear", "pronunciation": "/hɪər/", "meaning": "सुनना", "english_sentence": "Can you hear me?", "native_sentence": "क्या तुम मुझे सुन सकते हो?", "synonym": "Listen", "language": "hindi"},
  {"word": "See", "pronunciation": "/siː/", "meaning": "देखना", "english_sentence": "I see a bird.", "native_sentence": "मैं एक चिड़िया देखता हूँ।", "synonym": "View", "language": "hindi"},
  {"word": "Wait", "pronunciation": "/weɪt/", "meaning": "इंतज़ार करना", "english_sentence": "Wait for a minute.", "native_sentence": "एक मिनट इंतज़ार कीजिए।", "synonym": "Delay", "language": "hindi"},
  {"word": "Speak", "pronunciation": "/spiːk/", "meaning": "बोलना", "english_sentence": "Speak slowly please.", "native_sentence": "कृपया धीरे बोलिए।", "synonym": "Talk", "language": "hindi"},
  {"word": "Write", "pronunciation": "/raɪt/", "meaning": "लिखना", "english_sentence": "Write your name.", "native_sentence": "अपना नाम लिखिए।", "synonym": "Note", "language": "hindi"},
  {"word": "Read", "pronunciation": "/riːd/", "meaning": "पढ़ना", "english_sentence": "Read the lesson.", "native_sentence": "पाठ पढ़िए।", "synonym": "Study", "language": "hindi"},
  {"word": "Buy", "pronunciation": "/baɪ/", "meaning": "खरीदना", "english_sentence": "Buy some milk.", "native_sentence": "थोड़ा दूध खरीदिए।", "synonym": "Purchase", "language": "hindi"},
  {"word": "Sell", "pronunciation": "/sel/", "meaning": "बेचना", "english_sentence": "He sells apples.", "native_sentence": "वह सेब बेचता है।", "synonym": "Trade", "language": "hindi"},
  {"word": "Walk", "pronunciation": "/wɔːk/", "meaning": "चलना", "english_sentence": "Walk every morning.", "native_sentence": "हर सुबह चलिए।", "synonym": "Stroll", "language": "hindi"},
  {"word": "Sit", "pronunciation": "/sɪt/", "meaning": "बैठना", "english_sentence": "Sit down please.", "native_sentence": "कृपया बैठिए।", "synonym": "Rest", "language": "hindi"},
  {"word": "Morning", "pronunciation": "/ˈmɔːrnɪŋ/", "meaning": "सुबह", "english_sentence": "I wake up in the morning.", "native_sentence": "मैं सुबह उठता हूँ।", "synonym": "Dawn", "language": "hindi"},
  {"word": "Evening", "pronunciation": "/ˈiːvnɪŋ/", "meaning": "शाम", "english_sentence": "We walk in the evening.", "native_sentence": "हम शाम को टहलते हैं।", "synonym": "Dusk", "language": "hindi"},
  {"word": "Week", "pronunciation": "/wiːk/", "meaning": "हफ्ता", "english_sentence": "There are seven days in a week.", "native_sentence": "एक हफ्ते में सात दिन होते हैं।", "synonym": "Cycle", "language": "hindi"},
  {"word": "Month", "pronunciation": "/mʌnθ/", "meaning": "महीना", "english_sentence": "January is the first month.", "native_sentence": "जनवरी पहला महीना है।", "synonym": "Period", "language": "hindi"},
  {"word": "Year", "pronunciation": "/jɪər/", "meaning": "वर्ष", "english_sentence": "Happy new year.", "native_sentence": "नव वर्ष की शुभकामनाएँ।", "synonym": "Era", "language": "hindi"},
  {"word": "Bicycle", "pronunciation": "/ˈbaɪsɪkl/", "meaning": "साइकिल", "english_sentence": "I ride my bicycle.", "native_sentence": "मैं अपनी साइकिल चलाता हूँ।", "synonym": "Cycle", "language": "hindi"},
  {"word": "Bus", "pronunciation": "/bʌs/", "meaning": "बस", "english_sentence": "The bus is late.", "native_sentence": "बस देर से है।", "synonym": "Coach", "language": "hindi"},
  {"word": "Airplane", "pronunciation": "/ˈerpleɪn/", "meaning": "हवाई जहाज़", "english_sentence": "The airplane is in the sky.", "native_sentence": "हवाई जहाज़ आसमान में है।", "synonym": "Aircraft", "language": "hindi"},
  {"word": "Boat", "pronunciation": "/boʊt/", "meaning": "नाव", "english_sentence": "The boat is on the lake.", "native_sentence": "नाव झील में है।", "synonym": "Ship", "language": "hindi"},
  {"word": "Head", "pronunciation": "/hed/", "meaning": "सिर", "english_sentence": "Protect your head.", "native_sentence": "अपने सिर की रक्षा करें।", "synonym": "Skull", "language": "hindi"},
  {"word": "Shoulder", "pronunciation": "/ˈʃoʊldər/", "meaning": "कंधा", "english_sentence": "He has broad shoulders.", "native_sentence": "उसके कंधे चौड़े हैं।", "synonym": "Joint", "language": "hindi"},
  {"word": "Arm", "pronunciation": "/ɑːrm/", "meaning": "बाँह", "english_sentence": "Stretch your arm.", "native_sentence": "अपनी बाँह फैलाएँ।", "synonym": "Limb", "language": "hindi"},
  {"word": "Leg", "pronunciation": "/leɡ/", "meaning": "पैर", "english_sentence": "My leg is hurting.", "native_sentence": "मेरा पैर दर्द कर रहा है।", "synonym": "Member", "language": "hindi"},
  {"word": "Finger", "pronunciation": "/ˈfɪŋɡər/", "meaning": "उँगली", "english_sentence": "I have ten fingers.", "native_sentence": "मेरी दस उँगलियाँ हैं।", "synonym": "Digit", "language": "hindi"},
  {"word": "Medicine", "pronunciation": "/ˈmedsn/", "meaning": "दवा", "english_sentence": "Take your medicine.", "native_sentence": "अपनी दवा लें।", "synonym": "Drug", "language": "hindi"},
  {"word": "Doctor", "pronunciation": "/ˈdɒktər/", "meaning": "डॉक्टर", "english_sentence": "Go to the doctor.", "native_sentence": "डॉक्टर के पास जाएँ।", "synonym": "Physician", "language": "hindi"},
  {"word": "City", "pronunciation": "/ˈsɪti/", "meaning": "शहर", "english_sentence": "Kathmandu is a city.", "native_sentence": "काठमांडू एक शहर है।", "synonym": "Town", "language": "hindi"},
  {"word": "Village", "pronunciation": "/ˈvɪlɪdʒ/", "meaning": "गाँव", "english_sentence": "My village is small.", "native_sentence": "मेरा गाँव छोटा है।", "synonym": "Hamlet", "language": "hindi"},
  {"word": "Market", "pronunciation": "/ˈmɑːrkɪt/", "meaning": "बाज़ार", "english_sentence": "The market is crowded.", "native_sentence": "बाज़ार में भीड़ है।", "synonym": "Bazaar", "language": "hindi"},
  {"word": "Shop", "pronunciation": "/ʃɒp/", "meaning": "दुकान", "english_sentence": "The shop is open.", "native_sentence": "दुकान खुली है।", "synonym": "Store", "language": "hindi"},
  {"word": "Money", "pronunciation": "/ˈmʌni/", "meaning": "पैसा", "english_sentence": "I need some money.", "native_sentence": "मुझे कुछ पैसे चाहिए।", "synonym": "Cash", "language": "hindi"},
  {"word": "Price", "pronunciation": "/praɪs/", "meaning": "कीमत", "english_sentence": "What is the price?", "native_sentence": "कीमत क्या है?", "synonym": "Cost", "language": "hindi"},
  {"word": "Heavy", "pronunciation": "/ˈhevi/", "meaning": "भारी", "english_sentence": "This box is heavy.", "native_sentence": "यह डिब्बा भारी है।", "synonym": "Weighty", "language": "hindi"},
  {"word": "Light", "pronunciation": "/laɪt/", "meaning": "हल्का", "english_sentence": "The bag is light.", "native_sentence": "बैग हल्का है।", "synonym": "Weightless", "language": "hindi"},
  {"word": "Fast", "pronunciation": "/fæst/", "meaning": "तेज़", "english_sentence": "He runs fast.", "native_sentence": "वह तेज़ दौड़ता है।", "synonym": "Rapid", "language": "hindi"},
  {"word": "Dry", "pronunciation": "/draɪ/", "meaning": "सूखा", "english_sentence": "The cloth is dry.", "native_sentence": "कपड़ा सूखा है।", "synonym": "Arid", "language": "hindi"},
  {"word": "Wet", "pronunciation": "/wet/", "meaning": "गीला", "english_sentence": "The floor is wet.", "native_sentence": "फ़र्श गीला है।", "synonym": "Damp", "language": "hindi"},
  {"word": "Easy", "pronunciation": "/ˈiːzi/", "meaning": "आसान", "english_sentence": "This task is easy.", "native_sentence": "यह काम आसान है।", "synonym": "Simple", "language": "hindi"},
  {"word": "Hard", "pronunciation": "/hɑːrd/", "meaning": "कठिन", "english_sentence": "The exam was hard.", "native_sentence": "परीक्षा कठिन थी।", "synonym": "Difficult", "language": "hindi"},
  {"word": "Rough", "pronunciation": "/rʌf/", "meaning": "खुरदुरा", "english_sentence": "The wall is rough.", "native_sentence": "दीवार खुरदुरी है।", "synonym": "Coarse", "language": "hindi"},
  {"word": "Safe", "pronunciation": "/seɪf/", "meaning": "सुरक्षित", "english_sentence": "Drive safe.", "native_sentence": "सुरक्षित चलाएँ।", "synonym": "Secure", "language": "hindi"},
  {"word": "Danger", "pronunciation": "/ˈdeɪndʒər/", "meaning": "खतरा", "english_sentence": "Fire is a danger.", "native_sentence": "आग एक खतरा है।", "synonym": "Hazard", "language": "hindi"},
  {"word": "Think", "pronunciation": "/θɪŋk/", "meaning": "सोचना", "english_sentence": "Think before you speak.", "native_sentence": "बोलने से पहले सोचें।", "synonym": "Ponder", "language": "hindi"},
  {"word": "Learn", "pronunciation": "/lɜːrn/", "meaning": "सीखना", "english_sentence": "I want to learn English.", "native_sentence": "मैं अंग्रेज़ी सीखना चाहता हूँ।", "synonym": "Gain", "language": "hindi"},
  {"word": "Teach", "pronunciation": "/tiːtʃ/", "meaning": "सिखाना", "english_sentence": "She will teach us.", "native_sentence": "वह हमें सिखाएगी।", "synonym": "Instruct", "language": "hindi"},
  {"word": "Find", "pronunciation": "/faɪnd/", "meaning": "खोजना", "english_sentence": "I can't find my keys.", "native_sentence": "मैं अपनी चाबियाँ नहीं ढूँढ पा रहा हूँ।", "synonym": "Discover", "language": "hindi"},
  {"word": "Lose", "pronunciation": "/luːz/", "meaning": "खोना", "english_sentence": "Don't lose your phone.", "native_sentence": "अपना फ़ोन मत खोइए।", "synonym": "Misplace", "language": "hindi"},
  {"word": "Give", "pronunciation": "/ɡɪv/", "meaning": "देना", "english_sentence": "Give me a pen.", "native_sentence": "मुझे एक कलम दीजिए।", "synonym": "Grant", "language": "hindi"},
  {"word": "Take", "pronunciation": "/teɪk/", "meaning": "लेना", "english_sentence": "Take a seat.", "native_sentence": "कृपया बैठिए।", "synonym": "Fetch", "language": "hindi"},
  {"word": "Dream", "pronunciation": "/driːm/", "meaning": "सपना", "english_sentence": "I had a good dream.", "native_sentence": "मैंने अच्छा सपना देखा।", "synonym": "Vision", "language": "hindi"},
  {"word": "Answer", "pronunciation": "/ˈɑːnsər/", "meaning": "उत्तर", "english_sentence": "Give me an answer.", "native_sentence": "मुझे उत्तर दीजिए।", "synonym": "Reply", "language": "hindi"},
  {"word": "Question", "pronunciation": "/ˈkwestʃən/", "meaning": "प्रश्न", "english_sentence": "Ask a question.", "native_sentence": "एक प्रश्न पूछिए।", "synonym": "Inquiry", "language": "hindi"},
  {"word": "Wall", "pronunciation": "/wɔːl/", "meaning": "दीवार", "english_sentence": "The wall is white.", "native_sentence": "दीवार सफ़ेद है।", "synonym": "Partition", "language": "hindi"},
  {"word": "Floor", "pronunciation": "/flɔːr/", "meaning": "फ़र्श", "english_sentence": "Clean the floor.", "native_sentence": "फ़र्श साफ़ कीजिए।", "synonym": "Deck", "language": "hindi"},
  {"word": "Roof", "pronunciation": "/ruːf/", "meaning": "छत", "english_sentence": "The roof is leaking.", "native_sentence": "छत से पानी टपक रहा है।", "synonym": "Ceiling", "language": "hindi"},
  {"word": "Earth", "pronunciation": "/ɜːrθ/", "meaning": "पृथ्वी", "english_sentence": "We live on Earth.", "native_sentence": "हम पृथ्वी पर रहते हैं।", "synonym": "Planet", "language": "hindi"},
  {"word": "Football", "pronunciation": "/ˈfʊtbɔːl/", "meaning": "फुटबॉल", "english_sentence": "He plays football.", "native_sentence": "वह फुटबॉल खेलता है।", "synonym": "Soccer", "language": "hindi"},
  {"word": "Game", "pronunciation": "/ɡeɪm/", "meaning": "खेल", "english_sentence": "I like this game.", "native_sentence": "मुझे यह खेल पसंद है।", "synonym": "Match", "language": "hindi"},
  {"word": "Ball", "pronunciation": "/bɔːl/", "meaning": "गेंद", "english_sentence": "Throw the ball.", "native_sentence": "गेंद फेंको।", "synonym": "Sphere", "language": "hindi"},
  {"word": "Team", "pronunciation": "/tiːm/", "meaning": "टीम", "english_sentence": "Our team is strong.", "native_sentence": "हमारी टीम मजबूत है।", "synonym": "Group", "language": "hindi"},
  {"word": "Race", "pronunciation": "/reɪs/", "meaning": "दौड़", "english_sentence": "He won the race.", "native_sentence": "उसने दौड़ जीती।", "synonym": "Sprint", "language": "hindi"},
  {"word": "Exercise", "pronunciation": "/ˈeksərsaɪz/", "meaning": "व्यायाम", "english_sentence": "Exercise daily.", "native_sentence": "रोज़ व्यायाम करें।", "synonym": "Workout", "language": "hindi"},
  {"word": "Healthy", "pronunciation": "/ˈhelθi/", "meaning": "स्वस्थ", "english_sentence": "Eat healthy food.", "native_sentence": "स्वस्थ भोजन करें।", "synonym": "Fit", "language": "hindi"},
  {"word": "Power", "pronunciation": "/ˈpaʊər/", "meaning": "शक्ति", "english_sentence": "Knowledge is power.", "native_sentence": "ज्ञान ही शक्ति है।", "synonym": "Strength", "language": "hindi"},
  {"word": "Internet", "pronunciation": "/ˈɪntərnet/", "meaning": "इंटरनेट", "english_sentence": "The internet is slow.", "native_sentence": "इंटरनेट धीमा है।", "synonym": "Web", "language": "hindi"},
  {"word": "Email", "pronunciation": "/ˈiːmeɪl/", "meaning": "ईमेल", "english_sentence": "Send me an email.", "native_sentence": "मुझे ईमेल भेजो।", "synonym": "Message", "language": "hindi"},
  {"word": "Website", "pronunciation": "/ˈwebsaɪt/", "meaning": "वेबसाइट", "english_sentence": "Visit our website.", "native_sentence": "हमारी वेबसाइट देखें।", "synonym": "Site", "language": "hindi"},
  {"word": "Password", "pronunciation": "/ˈpæswɜːrd/", "meaning": "पासवर्ड", "english_sentence": "Keep your password safe.", "native_sentence": "अपना पासवर्ड सुरक्षित रखें।", "synonym": "Code", "language": "hindi"},
  {"word": "Video", "pronunciation": "/ˈvɪdioʊ/", "meaning": "वीडियो", "english_sentence": "Watch this video.", "native_sentence": "यह वीडियो देखें।", "synonym": "Clip", "language": "hindi"},
  {"word": "Photo", "pronunciation": "/ˈfoʊtoʊ/", "meaning": "फोटो", "english_sentence": "This is a nice photo.", "native_sentence": "यह एक अच्छी फोटो है।", "synonym": "Image", "language": "hindi"},
  {"word": "Message", "pronunciation": "/ˈmesɪdʒ/", "meaning": "संदेश", "english_sentence": "I got your message.", "native_sentence": "मुझे तुम्हारा संदेश मिला।", "synonym": "Note", "language": "hindi"},
  {"word": "Call", "pronunciation": "/kɔːl/", "meaning": "फोन कॉल", "english_sentence": "Give me a call.", "native_sentence": "मुझे कॉल करो।", "synonym": "Ring", "language": "hindi"},
  {"word": "Noise", "pronunciation": "/nɔɪz/", "meaning": "शोर", "english_sentence": "Stop making noise.", "native_sentence": "शोर करना बंद करो।", "synonym": "Din", "language": "hindi"},
  {"word": "Quiet", "pronunciation": "/ˈkwaɪət/", "meaning": "शांत", "english_sentence": "The library is quiet.", "native_sentence": "पुस्तकालय शांत है।", "synonym": "Silent", "language": "hindi"},
  {"word": "Talk", "pronunciation": "/tɔːk/", "meaning": "बात करना", "english_sentence": "We need to talk.", "native_sentence": "हमें बात करनी है।", "synonym": "Speak", "language": "hindi"},
  {"word": "Listen", "pronunciation": "/ˈlɪsn/", "meaning": "सुनना", "english_sentence": "Listen to the teacher.", "native_sentence": "शिक्षक की बात सुनो।", "synonym": "Hear", "language": "hindi"},
  {"word": "Care", "pronunciation": "/keər/", "meaning": "देखभाल", "english_sentence": "Take care of yourself.", "native_sentence": "अपना ख्याल रखना।", "synonym": "Attention", "language": "hindi"},
  {"word": "Respect", "pronunciation": "/rɪˈspekt/", "meaning": "सम्मान", "english_sentence": "Respect your elders.", "native_sentence": "बड़ों का सम्मान करो।", "synonym": "Honor", "language": "hindi"},
  {"word": "Kindness", "pronunciation": "/ˈkaɪndnəs/", "meaning": "दया", "english_sentence": "Kindness is a virtue.", "native_sentence": "दया एक गुण है।", "synonym": "Goodness", "language": "hindi"},
  {"word": "Family", "pronunciation": "/ˈfæmɪli/", "meaning": "परिवार", "english_sentence": "I love my family.", "native_sentence": "मुझे अपना परिवार पसंद है।", "synonym": "Kin", "language": "hindi"},
  {"word": "Neighbor", "pronunciation": "/ˈneɪbər/", "meaning": "पड़ोसी", "english_sentence": "My neighbor is helpful.", "native_sentence": "मेरा पड़ोसी मददगार है।", "synonym": "Nearby person", "language": "hindi"},
  {"word": "Guest", "pronunciation": "/ɡest/", "meaning": "अतिथि", "english_sentence": "The guest is here.", "native_sentence": "अतिथि यहाँ हैं।", "synonym": "Visitor", "language": "hindi"},
  {"word": "Party", "pronunciation": "/ˈpɑːrti/", "meaning": "पार्टी", "english_sentence": "Let's go to the party.", "native_sentence": "चलो पार्टी में चलते हैं।", "synonym": "Celebration", "language": "hindi"},
  {"word": "Holiday", "pronunciation": "/ˈhɒlədeɪ/", "meaning": "छुट्टी", "english_sentence": "Today is a holiday.", "native_sentence": "आज छुट्टी है।", "synonym": "Vacation", "language": "hindi"},
  {"word": "Journey", "pronunciation": "/ˈdʒɜːrni/", "meaning": "यात्रा", "english_sentence": "The journey was long.", "native_sentence": "यात्रा लंबी थी।", "synonym": "Trip", "language": "hindi"},
  {"word": "Safety", "pronunciation": "/ˈseɪfti/", "meaning": "सुरक्षा", "english_sentence": "Safety comes first.", "native_sentence": "सुरक्षा सबसे पहले आती है।", "synonym": "Protection", "language": "hindi"},
  {"word": "Lucky", "pronunciation": "/ˈlʌki/", "meaning": "भाग्यशाली", "english_sentence": "You are very lucky.", "native_sentence": "तुम बहुत भाग्यशाली हो।", "synonym": "Fortunate", "language": "hindi"},
  {"word": "Special", "pronunciation": "/ˈspeʃl/", "meaning": "विशेष", "english_sentence": "Today is a special day.", "native_sentence": "आज एक विशेष दिन है।", "synonym": "Unique", "language": "hindi"},
  {"word": "Simple", "pronunciation": "/ˈsɪmpl/", "meaning": "सरल", "english_sentence": "It is a simple question.", "native_sentence": "यह एक सरल प्रश्न है।", "synonym": "Easy", "language": "hindi"},
  {"word": "Modern", "pronunciation": "/ˈmɒdərn/", "meaning": "आधुनिक", "english_sentence": "This is a modern house.", "native_sentence": "यह एक आधुनिक घर है।", "synonym": "New", "language": "hindi"},
  {"word": "Beautiful", "pronunciation": "/ˈbjuːtɪfl/", "meaning": "सुंदर", "english_sentence": "The weather is beautiful.", "native_sentence": "मौसम सुंदर है।", "synonym": "Pretty", "language": "hindi"},
  {"word": "Boring", "pronunciation": "/ˈbɔːrɪŋ/", "meaning": "उबाऊ", "english_sentence": "The movie was boring.", "native_sentence": "फिल्म उबाऊ थी।", "synonym": "Dull", "language": "hindi"},
  {"word": "Exciting", "pronunciation": "/ɪkˈsaɪtɪŋ/", "meaning": "रोमांचक", "english_sentence": "The match was exciting.", "native_sentence": "मैच रोमांचक था।", "synonym": "Thrilling", "language": "hindi"},
  {"word": "Afraid", "pronunciation": "/əˈfreɪd/", "meaning": "डरा हुआ", "english_sentence": "Don't be afraid.", "native_sentence": "डरो मत।", "synonym": "Scared", "language": "hindi"},
  {"word": "Smart", "pronunciation": "/smɑːrt/", "meaning": "होशियार", "english_sentence": "He is a smart boy.", "native_sentence": "वह एक होशियार लड़का है।", "synonym": "Clever", "language": "hindi"},
  {"word": "Lazy", "pronunciation": "/ˈleɪzi/", "meaning": "आलसी", "english_sentence": "Don't be lazy.", "native_sentence": "आलसी मत बनो।", "synonym": "Idle", "language": "hindi"},
  {"word": "Busy", "pronunciation": "/ˈbɪzi/", "meaning": "व्यस्त", "english_sentence": "I am busy today.", "native_sentence": "मैं आज व्यस्त हूँ।", "synonym": "Active", "language": "hindi"},
  {"word": "Warm", "pronunciation": "/wɔːrm/", "meaning": "गर्म", "english_sentence": "The sun is warm.", "native_sentence": "धूप गर्म है।", "synonym": "Teepid", "language": "hindi"},
  {"word": "Chilly", "pronunciation": "/ˈtʃɪli/", "meaning": "ठंडा", "english_sentence": "The morning is chilly.", "native_sentence": "सुबह ठंडी है।", "synonym": "Cold", "language": "hindi"},
  {"word": "Taste", "pronunciation": "/teɪst/", "meaning": "स्वाद", "english_sentence": "The food has a good taste.", "native_sentence": "खाने का स्वाद अच्छा है।", "synonym": "Flavor", "language": "hindi"},
  {"word": "Smell", "pronunciation": "/smel/", "meaning": "गंध", "english_sentence": "I like the smell of flowers.", "native_sentence": "मुझे फूलों की खुशबू पसंद है।", "synonym": "Scent", "language": "hindi"},
  {"word": "Touch", "pronunciation": "/tʌtʃ/", "meaning": "छूना", "english_sentence": "Don't touch the wire.", "native_sentence": "तार को मत छूओ।", "synonym": "Contact", "language": "hindi"},
  {"word": "Sunny", "pronunciation": "/ˈsʌni/", "meaning": "धूप वाला", "english_sentence": "It is a sunny day.", "native_sentence": "आज धूप वाला दिन है।", "synonym": "Bright", "language": "hindi"},
  {"word": "Cloudy", "pronunciation": "/ˈklaʊdi/", "meaning": "बादलों से घिरा", "english_sentence": "The sky is cloudy.", "native_sentence": "आसमान में बादल छाए हुए हैं।", "synonym": "Overcast", "language": "hindi"},
  {"word": "Foggy", "pronunciation": "/ˈfɒɡi/", "meaning": "कोहरे वाला", "english_sentence": "It is foggy this morning.", "native_sentence": "आज सुबह कोहरा है।", "synonym": "Misty", "language": "hindi"},
  {"word": "Windy", "pronunciation": "/ˈwɪndi/", "meaning": "हवादार", "english_sentence": "It is a windy afternoon.", "native_sentence": "दोपहर हवादार है।", "synonym": "Breezy", "language": "hindi"},
  {"word": "Snow", "pronunciation": "/snoʊ/", "meaning": "बर्फ", "english_sentence": "I like to play in the snow.", "native_sentence": "मुझे बर्फ में खेलना पसंद है।", "synonym": "Frost", "language": "hindi"},
  {"word": "East", "pronunciation": "/iːst/", "meaning": "पूर्व", "english_sentence": "The sun rises in the east.", "native_sentence": "सूरज पूर्व में उगता है।", "synonym": "Orient", "language": "hindi"},
  {"word": "West", "pronunciation": "/west/", "meaning": "पश्चिम", "english_sentence": "The sun sets in the west.", "native_sentence": "सूरज पश्चिम में डूबता है।", "synonym": "Occident", "language": "hindi"},
  {"word": "North", "pronunciation": "/nɔːrθ/", "meaning": "उत्तर", "english_sentence": "The mountains are in the north.", "native_sentence": "पहाड़ उत्तर में हैं।", "synonym": "Arctic", "language": "hindi"},
  {"word": "South", "pronunciation": "/saʊθ/", "meaning": "दक्षिण", "english_sentence": "Birds fly to the south.", "native_sentence": "पक्षी दक्षिण की ओर उड़ते हैं।", "synonym": "Austral", "language": "hindi"},
  {"word": "Up", "pronunciation": "/ʌp/", "meaning": "ऊपर", "english_sentence": "Look up at the sky.", "native_sentence": "आसमान की ओर ऊपर देखो।", "synonym": "Above", "language": "hindi"},
  {"word": "Down", "pronunciation": "/daʊn/", "meaning": "नीचे", "english_sentence": "Sit down on the floor.", "native_sentence": "फर्श पर नीचे बैठो।", "synonym": "Below", "language": "hindi"},
  {"word": "Inside", "pronunciation": "/ˌɪnˈsaɪd/", "meaning": "अंदर", "english_sentence": "Come inside the house.", "native_sentence": "घर के अंदर आओ।", "synonym": "Within", "language": "hindi"},
  {"word": "Outside", "pronunciation": "/ˌaʊtˈsaɪd/", "meaning": "बाहर", "english_sentence": "It is cold outside.", "native_sentence": "बाहर ठंड है।", "synonym": "Exterior", "language": "hindi"},
  {"word": "Near", "pronunciation": "/nɪər/", "meaning": "पास", "english_sentence": "The shop is near my house.", "native_sentence": "दुकान मेरे घर के पास है।", "synonym": "Close", "language": "hindi"},
  {"word": "Far", "pronunciation": "/fɑːr/", "meaning": "दूर", "english_sentence": "The school is very far.", "native_sentence": "स्कूल बहुत दूर है।", "synonym": "Distant", "language": "hindi"},
  {"word": "Front", "pronunciation": "/frʌnt/", "meaning": "सामने", "english_sentence": "Stand in front of me.", "native_sentence": "मेरे सामने खड़े हो।", "synonym": "Forward", "language": "hindi"},
  {"word": "Back", "pronunciation": "/bæk/", "meaning": "पीछे", "english_sentence": "The garden is in the back.", "native_sentence": "बगीचा पीछे है।", "synonym": "Rear", "language": "hindi"},
  {"word": "Between", "pronunciation": "/bɪˈtwiːn/", "meaning": "के बीच", "english_sentence": "Stand between your parents.", "native_sentence": "अपने माता-पिता के बीच खड़े हो।", "synonym": "Amid", "language": "hindi"},
  {"word": "Wake up", "pronunciation": "/weɪk ʌp/", "meaning": "जागना", "english_sentence": "I wake up early.", "native_sentence": "मैं जल्दी जागता हूँ।", "synonym": "Arise", "language": "hindi"},
  {"word": "Wash", "pronunciation": "/wɒʃ/", "meaning": "धोना", "english_sentence": "Wash your face.", "native_sentence": "अपना चेहरा धोओ।", "synonym": "Cleanse", "language": "hindi"},
  {"word": "Brush", "pronunciation": "/brʌʃ/", "meaning": "ब्रश करना", "english_sentence": "Brush your teeth.", "native_sentence": "अपने दांत ब्रश करो।", "synonym": "Sweep", "language": "hindi"},
  {"word": "Comb", "pronunciation": "/koʊm/", "meaning": "कंघी करना", "english_sentence": "Comb your hair.", "native_sentence": "अपने बालों में कमघी करो।", "synonym": "Groom", "language": "hindi"},
  {"word": "Dress", "pronunciation": "/dres/", "meaning": "कपड़े पहनना", "english_sentence": "Get dressed quickly.", "native_sentence": "जल्दी कपड़े पहनो।", "synonym": "Clothe", "language": "hindi"},
  {"word": "Drive", "pronunciation": "/draɪv/", "meaning": "गाड़ी चलाना", "english_sentence": "He can drive a car.", "native_sentence": "वह गाड़ी चला सकता है।", "synonym": "Steer", "language": "hindi"},
  {"word": "Ride", "pronunciation": "/raɪd/", "meaning": "सवारी करना", "english_sentence": "I ride a bicycle.", "native_sentence": "मैं साइकिल चलाता हूँ।", "synonym": "Travel", "language": "hindi"},
  {"word": "Push", "pronunciation": "/pʊʃ/", "meaning": "धक्का देना", "english_sentence": "Push the door open.", "native_sentence": "दरवाज़ा धक्का देकर खोलो।", "synonym": "Shove", "language": "hindi"},
  {"word": "Pull", "pronunciation": "/pʊl/", "meaning": "खींचना", "english_sentence": "Pull the rope.", "native_sentence": "रस्सी खींचो।", "synonym": "Drag", "language": "hindi"},
  {"word": "Carry", "pronunciation": "/ˈkæri/", "meaning": "उठाना", "english_sentence": "Carry this bag.", "native_sentence": "यह बैग उठाओ।", "synonym": "Hold", "language": "hindi"},
  {"word": "Hold", "pronunciation": "/hoʊld/", "meaning": "पकड़ना", "english_sentence": "Hold my hand.", "native_sentence": "मेरा हाथ पकड़ो।", "synonym": "Grasp", "language": "hindi"},
  {"word": "Drop", "pronunciation": "/drɒp/", "meaning": "गिराना", "english_sentence": "Don't drop the glass.", "native_sentence": "गिलास मत गिराओ।", "synonym": "Fall", "language": "hindi"},
  {"word": "Choose", "pronunciation": "/tʃuːz/", "meaning": "चुनना", "english_sentence": "Choose one color.", "native_sentence": "एक रंग चुनो।", "synonym": "Select", "language": "hindi"},
  {"word": "Pay", "pronunciation": "/peɪ/", "meaning": "भुगतान करना", "english_sentence": "Pay the bill.", "native_sentence": "बिल का भुगतान करो।", "synonym": "Settle", "language": "hindi"},
  {"word": "Kind", "pronunciation": "/kaɪnd/", "meaning": "दयालु", "english_sentence": "He is a very kind man.", "native_sentence": "वह बहुत दयालु आदमी है।", "synonym": "Gentle", "language": "hindi"},
  {"word": "Cruel", "pronunciation": "/ˈkruːəl/", "meaning": "निर्दयी", "english_sentence": "Hunting is cruel.", "native_sentence": "शिकार करना निर्दयी है।", "synonym": "Mean", "language": "hindi"}
];
